import sqlite3

# SQLite3 Datatypes:
# NULL
# INTEGER
# REAL
# TEXT
# BLOB

def create_tables():
    dbcon = sqlite3.connect("instance/db.db")
    cursor = dbcon.cursor()
    
    ##creat etables

    cursor.execute("""
            CREATE TABLE IF NOT EXISTS KundenAccount(
            Username TEXT PRIMARY KEY NOT NULL,
            Passwort TEXT NOT NULL,
            Nachname TEXT NOT NULL,
            Vorname TEXT NOT NULL,
            Strasse TEXT NOT NULL,
            Hausnummer INTEGER NOT NULL,
            Plz INTEGER NOT NULL
        )""")

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS GeschaeftsAccount(
            Username TEXT PRIMARY KEY NOT NULL,
            Passwort TEXT NOT NULL,
            Restaurantname TEXT NOT NULL,
            Beschreibung TEST NOT NULL,
            Strasse TEXT NOT NULL,
            Hausnummer INTEGER NOT NULL,
            Plz INTEGER NOT NULL
        )""")

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS Oeffnungszeit(
            GUsername TEXT NOT NULL,
            Wochentag TEXT NOT NULL CHECK(Wochentag IN ('Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag')),
            Von time NOT NULL,
            Bis time NOT NULL CHECK(Von < Bis),
            FOREIGN KEY (GUsername) REFERENCES GeschaeftsAccount(Username),
            PRIMARY KEY (GUsername, Wochentag)
        )""")

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS Item(
            ID INTEGER NOT NULL,
            Restaurant TEXT NOT NULL,
            Name TEXT NOT NULL,
            Kategorie TEXT CHECK(Kategorie IN ('Vorspeise', 'Hauptgericht', 'Dessert', 'Getränk')),
            IBeschreibung TEXT NOT NULL DEFAULT '',
            Preis INTEGER NOT NULL,
            Deaktiviert INTEGER DEFAULT 0 CHECK(Deaktiviert IN (0, 1)),
            PRIMARY KEY (ID),
            FOREIGN KEY (Restaurant) REFERENCES GeschaeftsAccount(username),
            UNIQUE(Restaurant, Name, Kategorie, IBeschreibung, Preis),
            UNIQUE(Restaurant, Name, Deaktiviert)                  
        );""")

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS Lieferradius(
            GUsername TEXT NOT NULL,
            Plz TEXT NOT NULL,
            FOREIGN KEY (GUsername) REFERENCES GeschaeftsAccount(Username),
            PRIMARY KEY (Plz, GUsername)
        )""")
    
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS Bestellung(
            KUsername TEXT NOT NULL,
            GUsername TEXT NOT NULL,
            Eingangszeit TEXT NOT NULL,
            Anmerkung TEXT,
            Bestellstatus TEXT NOT NULL CHECK( Bestellstatus IN ('in Bearbeitung','in Zubereitung','storniert','abgeschlossen') )
        )""")

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS bestellung_beinhaltet(
            Bestellung INTEGER NOT NULL,
            ItemID INTEGER NOT NULL,
            Menge INTEGER NOT NULL,
            FOREIGN KEY(Bestellung) REFERENCES Bestellung(ID)
            FOREIGN KEY(ItemID) REFERENCES Item(ID) ON DELETE CASCADE
        )""")
    
    
    ##insert data
    
    cursor.execute("""
        INSERT or IGNORE INTO KundenAccount (Username, Passwort, Nachname, Vorname, Strasse, Hausnummer, Plz)
        VALUES ('edge', 'weiter', 'Pascal', 'Ritzenfeld', 'Engerweg', 6, 47057)
        """)
    
    cursor.execute("""
        INSERT or IGNORE INTO GeschaeftsAccount (Username, Passwort, Restaurantname, Beschreibung, Strasse, Hausnummer, Plz)
        VALUES ('cafebluerose', '1234', 'Café Blue Rose', 'Café blue rose ist ein kleines, ruhiges Café in der Innenstadt. Unsere selbstgemachten Kuchen schmecken Klein und Groß.', 'Königstraße', 25, 46735), 
            ('sushiheaven', '1234', 'Sushi Heaven', 'Unsere Sushi- Meister, trainiert in Japan, zaubern euch authentisches Sushi.', 'Oststraße', 16, 45545),
            ('bowl', '1234', 'Bowl', 'Wir verkaufen verschiedene Bowls. Ihr könnt hier auch eigene Bowls zusammenstellen!', 'Landstraße', 165, 46323),
            ('americanstory', '1234', 'American Story', 'Das Konzept unseres Restaurants ist es die Geschichte Amerikas durch das Essen neu zu erleben.', 'An den Buchen', 18, 45432),
            ('sidebysoups', '1234', 'Side by Soups', 'Bei uns bekommst du Suppen aller Art. Unsere Rezepte kommen aus der ganzen Welt.', 'Ring des Lebens', 66, 49736),
            ('mamamiapizza', '1234', 'Mamamia Pizza', 'Authentische italienische Pizza frisch aus einem Steinofen liefern wir direkt vor deine Haustür.', 'Hohe Straße', 7, 47051),
            ('zoesgrill', '1234', 'Zoes Grill', 'Wir präsentieren Ihnen leckere Rezepte mit Hackfleisch, Schafskäse, Lamm, Grillgemüse, Grillspießen und vielem mehr.', 'Königsberger Allee', 113, 47058),
            ('mcdaniels', '1234', 'McDaniels', 'Wir lieben es.', 'Portsmouthpl.', 1, 47051),
            ('subday', '1234', 'Subday', 'Iss frisch!', 'Königstraße', 48, 47051),
            ('kfp', '1234', 'KFP', 'Kentucky Fried Poultry', 'Königstraße', 56, 47051),
            ('sunsetgrill', '1234', 'Sunset Grill', 'Erleben Sie eine Symphonie der Aromen bei Sunset Grill. Unsere kulinarischen Kreationen sind eine Feier von Geschmack und Ambiente.', 'Sonnenallee', 30, 45545),
            ('fusiondelight', '1234', 'Fusion Delight', 'Tauchen Sie ein in die Welt der Fusion-Küche bei Fusion Delight. Unsere Köche verbinden verschiedene kulinarische Traditionen für ein delikates Geschmackserlebnis.', 'Mischstraße', 42, 45545),
            ('spicynoodlehouse', '1234', 'Spicy Noodle House', 'Bereiten Sie sich auf ein feuriges Fest bei Spicy Noodle House vor. Unsere Nudeln sind mit kühnen Gewürzen durchtränkt und entfachen Ihre Geschmacksknospen.', 'Feuerweg', 5, 45545),
            ('greenoasiscafe', '1234', 'Green Oasis Cafe', 'Entfliehen Sie bei Green Oasis Cafe dem Alltag. Genießen Sie unsere Garten-inspirierten Leckereien in einer ruhigen Umgebung.', 'Gartenweg', 12, 45545),
            ('stellarsteaks', '1234', 'Stellar Steaks', 'Gönnen Sie sich das Beste bei Stellar Steaks. Unsere erfahrenen Köche garantieren, dass jedes Steak ein Meisterwerk aus Geschmack und Zartheit ist.', 'Sterngasse', 8, 45545),
            ('thaiharmony', '1234', 'Thai Harmony', 'Entdecken Sie die perfekte Balance von süß, sauer und scharf bei Thai Harmony. Unsere authentischen Thai-Gerichte entführen Sie in die Straßen von Bangkok.', 'Siamstraße', 14, 45545),
            ('cocoacraze', '1234', 'Cocoa Craze', 'Befriedigen Sie Ihre süßen Gelüste bei Cocoa Craze. Unsere schokoladengetränkten Kreationen sind ein himmlisches Vergnügen für Schokoladenliebhaber.', 'Schokoladenplatz', 21, 45545),
            ('mysticalmezze', '1234', 'Mystical Mezze', 'Begleiten Sie uns auf eine Reise durch die mediterranen Aromen bei Mystical Mezze. Unsere kleinen Häppchen sind ein Fest der Geschmacksvielfalt und Tradition.', 'Olivengasse', 33, 45545),
            ('saffronspice', '1234', 'Saffron Spice', 'Erleben Sie die Reichhaltigkeit von Aromen bei Saffron Spice. Unsere Gerichte sind durchzogen von der Wärme und dem Duft des besten Safrans.', 'Gewürzweg', 9, 45545),
            ('tropicaltaco', '1234', 'Tropical Taco', 'Entfliehen Sie mit jedem Bissen zu einem tropischen Paradies bei Tropical Taco. Unsere Tacos sind eine Fiesta aus lebendigen Aromen und frischen Zutaten.', 'Palmenstraße', 17, 45545),
            ('zwiebelzirkus', '1234', 'Zwiebel Zirkus', 'Willkommen im Zwiebel Zirkus! Tauchen Sie ein in die Welt der Zwiebeln mit unseren raffinierten Gerichten, die diesen vielseitigen Geschmacksträger zelebrieren.', 'Zwiebelallee', 22, 45545),
            ('wurstundsenf', '1234', 'Wurst und Senf', 'Herzlich willkommen im Wurst und Senf! Genießen Sie traditionelle deutsche Wurstspezialitäten mit einer Auswahl an hausgemachten Senfsorten.', 'Senfplatz', 11, 45545),
            ('rheinweinhaus', '1234', 'Rhein Weinhaus', 'Entdecken Sie die Welt des deutschen Weins im Rhein Weinhaus. Unsere erlesene Auswahl an Weinen begleitet köstliche Gerichte, die die Region widerspiegeln.', 'Weinstraße', 29, 45545),
            ('schwarzbrotstube', '1234', 'Schwarzbrot Stube', 'Genießen Sie die Herzlichkeit einer deutschen Bäckerei in der Schwarzbrot Stube. Unsere Brote werden nach traditionellen Rezepten gebacken und begeistern jeden Brotliebhaber.', 'Brotgasse', 16, 45545),
            ('pilzparadies', '1234', 'Pilz Paradies', 'Tauchen Sie ein in das Pilz Paradies! Unsere Gerichte mit frischen Pilzen bieten eine kulinarische Reise durch die Wälder Deutschlands.', 'Waldweg', 8, 45545),
            ('sauerkrautundwurst', '1234', 'Sauerkraut und Wurst', 'Ein Fest für Liebhaber von Sauerkraut und Wurst! Erleben Sie die perfekte Kombination dieser traditionellen deutschen Delikatessen in unserem gemütlichen Lokal.', 'Sauergasse', 21, 45545);
            """)
    
    cursor.execute("""
        INSERT or IGNORE INTO Lieferradius (Plz, GUsername)
        VALUES 
            (47137, 'sushiheaven'),
            (47119, 'sushiheaven'),
            (47058, 'sushiheaven'),
            (47059, 'sushiheaven'),

            (47137, 'bowl'),
            (47119, 'bowl'),
            (47058, 'bowl'),
            (47059, 'bowl'),

            (47137, 'americasstory'),
            (47119, 'americasstory'),
            (47058, 'americasstory'),
            (47059, 'americasstory'),

            (47137, 'sidebysoups'),
            (47119, 'sidebysoups'),
            (47058, 'sidebysoups'),
            (47059, 'sidebysoups'),

            (47059, 'mamamiapizza'),
            (47057, 'mamamiapizza'),
            (47051, 'mamamiapizza'),
            (47053, 'mamamiapizza'),

            (47166, 'zoesgrill'),
            (47139, 'zoesgrill'),
            (47167, 'zoesgrill'),
            (47169, 'zoesgrill'),

            (47138, 'subday'),
            (47166, 'subday'),
            (47139, 'subday'),
            (47167, 'subday'),

            (47139, 'kfp'),
            (47167, 'kfp'),
            (47169, 'kfp'),
            (47055, 'kfp'),

            (47167, 'sunsetgrill'),
            (47169, 'sunsetgrill'),
            (47055, 'sunsetgrill'),
            (47249, 'sunsetgrill'),

            (47179, 'fusiondelight'),
            (47178, 'fusiondelight'),
            (47226, 'fusiondelight'),
            (47239, 'fusiondelight'),

            (47178, 'spicynoodlehouse'),
            (47226, 'spicynoodlehouse'),
            (47239, 'spicynoodlehouse'),
            (47229, 'spicynoodlehouse'),

            (47239, 'greenoasiscafe'),
            (47229, 'greenoasiscafe'),
            (47228, 'greenoasiscafe'),
            (47199, 'greenoasiscafe'),

            (47199, 'stellarsteaks'),
            (47198, 'stellarsteaks'),
            (47178, 'stellarsteaks'),
            (47226, 'stellarsteaks'),

            (47199, 'thaiharmony'),
            (47198, 'thaiharmony'),
            (47178, 'thaiharmony'),
            (47226, 'thaiharmony'),

            (47138, 'cocoacraze'),
            (47166, 'cocoacraze'),
            (47139, 'cocoacraze'),
            (47167, 'cocoacraze'),

            (47139, 'mysticalmezze'),
            (47167, 'mysticalmezze'),
            (47169, 'mysticalmezze'),
            (47055, 'mysticalmezze'),

            (47167, 'saffronspice'),
            (47169, 'saffronspice'),
            (47055, 'saffronspice'),
            (47249, 'saffronspice'),

            (47199, 'tropicaltaco'),
            (47198, 'tropicaltaco'),
            (47178, 'tropicaltaco'),
            (47226, 'tropicaltaco'),

            (47198, 'zwiebelzirkus'),
            (47178, 'zwiebelzirkus'),
            (47226, 'zwiebelzirkus'),
            (47239, 'zwiebelzirkus'),

            (47226, 'wurstundsenf'),
            (47239, 'wurstundsenf'),
            (47229, 'wurstundsenf'),
            (47228, 'wurstundsenf'),

            (47138, 'rheinweinhaus'),
            (47166, 'rheinweinhaus'),
            (47139, 'rheinweinhaus'),
            (47167, 'rheinweinhaus'),

            (47167, 'schwarzbrotstube'),
            (47169, 'schwarzbrotstube'),
            (47055, 'schwarzbrotstube'),
            (47249, 'schwarzbrotstube'),

            (47169, 'pilzparadies'),
            (47055, 'pilzparadies'),
            (47249, 'pilzparadies'),
            (47269, 'pilzparadies'),

            (47249, 'sauerkrautundwurst'),
            (47269, 'sauerkrautundwurst'),
            (47259, 'sauerkrautundwurst'),
            (47179, 'sauerkrautundwurst'),
                   
            (47137, 'cafebluerose'),
            (47119, 'cafebluerose'),
            (47058, 'cafebluerose'),
            (47059, 'cafebluerose'),
            
            (47057, 'stellarsteaks'),
            (47057, 'zoesgrill'),
            
            (47137, 'mcdaniels'),
            (47119, 'mcdaniels'),
            (47058, 'mcdaniels'),
            (47059, 'mcdaniels'),
            (47057, 'mcdaniels'),
            (47051, 'mcdaniels'),
            (47053, 'mcdaniels'),
            (47279, 'mcdaniels'),
            (47138, 'mcdaniels'),
            (47166, 'mcdaniels'),
            (47139, 'mcdaniels'),
            (47167, 'mcdaniels'),
            (47169, 'mcdaniels'),
            (47055, 'mcdaniels'),
            (47249, 'mcdaniels'),
            (47269, 'mcdaniels'),
            (47259, 'mcdaniels'),
            (47179, 'mcdaniels'),
            (47178, 'mcdaniels'),
            (47226, 'mcdaniels'),
            (47239, 'mcdaniels'),
            (47229, 'mcdaniels'),
            (47228, 'mcdaniels'),
            (47199, 'mcdaniels'),
            (47198, 'mcdaniels'),
                   
            (47137, 'zoesgrill'),
            (47119, 'zoesgrill'),
            (47058, 'zoesgrill'),
            (47059, 'zoesgrill'),
            (47057, 'zoesgrill'),
            (47051, 'zoesgrill'),
            (47053, 'zoesgrill'),
            (47279, 'zoesgrill'),
            (47138, 'zoesgrill'),
            (47166, 'zoesgrill'),
            (47139, 'zoesgrill'),
            (47167, 'zoesgrill'),
            (47169, 'zoesgrill'),
            (47055, 'zoesgrill'),
            (47249, 'zoesgrill'),
            (47269, 'zoesgrill'),
            (47259, 'zoesgrill'),
            (47179, 'zoesgrill'),
            (47178, 'zoesgrill'),
            (47226, 'zoesgrill'),
            (47239, 'zoesgrill'),
            (47229, 'zoesgrill'),
            (47228, 'zoesgrill'),
            (47199, 'zoesgrill'),
            (47198, 'zoesgrill'),
                   
            (47057, 'cafebluerose'),
            (47057, 'sushiheaven'),
            (47057, 'bowl'),
            (47057, 'fusiondelight');
""")

    

    cursor.execute("""
        INSERT or IGNORE INTO Item (Restaurant, Kategorie, Name, Preis, IBeschreibung)
        VALUES ('mamamiapizza', 'Vorspeise', 'Bruschetta', 550, 'Gebackenes Brot mit Tomaten, Knoblauch und Basilikum.'),
            ('mamamiapizza', 'Vorspeise', 'Caprese-Salat', 650, 'Tomaten, Mozzarella, Basilikum und Olivenoel.'),
            ('mamamiapizza', 'Vorspeise', 'Knoblauchbrot', 500, 'Frisches Brot mit Knoblauchbutter.'),
            ('mamamiapizza', 'Vorspeise', 'Antipasti-Platte', 850, 'Verschiedene mediterrane Vorspeisen.'),
            ('mamamiapizza', 'Hauptgericht', 'Pizza Margherita', 750, 'Tomatensauce, Mozzarella und Basilikum.'),
            ('mamamiapizza', 'Hauptgericht', 'Pizza Quattro Formaggi', 800, 'Tomatensauce, Mozzarella, Gorgonzola, Parmesan und Ricotta.'),
            ('mamamiapizza', 'Hauptgericht', 'Pasta Bolognese', 700, 'Pasta mit hausgemachter Bolognesesauce.'),
            ('mamamiapizza', 'Hauptgericht', 'Lasagne al Forno', 850, 'Schichten von Pasta, Hackfleischsauce und Bechamelsauce, gebacken im Ofen.'),
            ('mamamiapizza', 'Hauptgericht', 'Risotto Funghi', 780, 'Risotto mit Pilzen, Parmesan und Troeffeloel.'),
            ('mamamiapizza', 'Hauptgericht', 'Calzone', 820, 'Gefüllte Teigtasche mit Tomatensauce, Mozzarella und verschiedenen Zutaten.'),
            ('mamamiapizza', 'Hauptgericht', 'Gnocchi Gorgonzola', 750, 'Kartoffelgnocchi in Gorgonzolasauce.'),
            ('mamamiapizza', 'Hauptgericht', 'Penne all Arrabbiata', 720, 'Penne mit scharfer Tomatensauce und Knoblauch.'),
            ('mamamiapizza', 'Hauptgericht', 'Linguine ai Frutti di Mare', 890, 'Linguine mit Meeresfrüchten, Knoblauch und Tomatensauce.'),
            ('mamamiapizza', 'Dessert', 'Tiramisu', 550, 'Loeffelbiskuit mit Kaffee getraenkt, geschichtet mit Mascarponecreme und Kakao.'),
            ('mamamiapizza', 'Dessert', 'Panna Cotta', 600, 'Gelatinecreme mit Vanillearoma, serviert mit Fruchtsauce.'),
            ('mamamiapizza', 'Getränk', 'Limonata', 350, 'Italienische Zitronenlimonade.'),
            ('mamamiapizza', 'Getränk', 'Aranciata', 350, 'Italienische Orangenlimonade.'),
            ('mamamiapizza', 'Getränk', 'Pellegrino', 400, 'Mineralwasser aus Italien.'),
            ('mamamiapizza', 'Getränk', 'Acqua Minerale', 300, 'Stilles Mineralwasser.'),
            
            ('sushiheaven', 'Vorspeise', 'Edamame', 450, 'Gedämpfte junge Sojabohnenschoten mit Meersalz.'),
            ('sushiheaven', 'Vorspeise', 'Gyoza', 600, 'Japanische Teigtaschen mit einer würzigen Füllung, gebraten oder gedämpft.'),
            ('sushiheaven', 'Vorspeise', 'Agedashi Tofu', 550, 'Frittierter Tofu mit Dashi-Sauce und Frühlingszwiebeln.'),
            ('sushiheaven', 'Vorspeise', 'Wakame Salat', 500, 'Meeresalgen-Salat mit Sesam und Sojasauce.'),
            ('sushiheaven', 'Hauptgericht', 'Sushi Mix', 800, 'Verschiedene Sushi-Variationen mit Reis, Fisch und Gemüse.'),
            ('sushiheaven', 'Hauptgericht', 'Sashimi Teller', 850, 'Dünne Scheiben roher Fisch, serviert mit Sojasauce und Wasabi.'),
            ('sushiheaven', 'Hauptgericht', 'Tempura Udon', 750, 'Dicke Udon-Nudeln in einer klaren Brühe mit knusprigem Tempura.'),
            ('sushiheaven', 'Hauptgericht', 'Chirashi Bowl', 820, 'Schüssel mit Reis, belegt mit einer Vielzahl von rohem Fisch und Gemüse.'),
            ('sushiheaven', 'Hauptgericht', 'Dragon Roll', 780, 'Makizushi-Rolle mit Lachs, Gurke, Avocado und einem Mantel aus Avocado.'),
            ('sushiheaven', 'Hauptgericht', 'Rainbow Roll', 880, 'Makizushi-Rolle mit verschiedenen Fischsorten und Avocado.'),
            ('sushiheaven', 'Hauptgericht', 'Unagi Don', 900, 'Gegrillter Aal auf Reis, serviert mit einer speziellen Sauce.'),
            ('sushiheaven', 'Hauptgericht', 'Yakitori Spieße', 720, 'Gegrillte Hühnerspieße mit Teriyaki-Sauce.'),
            ('sushiheaven', 'Hauptgericht', 'Sushi Burger', 850, 'Sushi-Belag zwischen Reisbrot, serviert wie ein Burger.'),
            ('sushiheaven', 'Dessert', 'Matcha Eis', 500, 'Grünes Tee-Eis, cremig und erfrischend.'),
            ('sushiheaven', 'Dessert', 'Mochi', 550, 'Japanische Reiskuchen mit süßer Füllung, oft mit Eiscreme.'),
            ('sushiheaven', 'Getränk', 'Grüner Tee', 300, 'Früher grüner Tee aus Japan mit einem leicht herben Geschmack.'),
            ('sushiheaven', 'Getränk', 'Sake', 600, 'Traditioneller japanischer Reiswein mit verschiedenen Sorten.'),
            ('sushiheaven', 'Getränk', 'Ramune', 350, 'Japanisches kohlensäurehaltiges Erfrischungsgetränk mit Kugelverschluss.'),
            ('sushiheaven', 'Getränk', 'Lychee Eistee', 400, 'Eistee mit dem süßen Geschmack von Lychee-Früchten.'),
                   
            ('bowl', 'Vorspeise', 'Edamame Bowl', 550, 'Edamame-Bohnen serviert in einer Schüssel, mit Meersalz bestreut.'),
            ('bowl', 'Vorspeise', 'Avocado Hummus', 600, 'Hummus mit cremiger Avocado, serviert mit Pita-Brot.'),
            ('bowl', 'Vorspeise', 'Kimchi Pfannkuchen', 500, 'Koreanischer Pfannkuchen mit Kimchi und Gemüse.'),
            ('bowl', 'Vorspeise', 'Thai Sommerrollen', 650, 'Frische Frühlingsrollen mit Gemüse, Kräutern und Reisnudeln, serviert mit Erdnusssauce.'),
            ('bowl', 'Hauptgericht', 'Teriyaki Hähnchen Bowl', 750, 'Reisbowl mit gegrilltem Teriyaki-Hähnchen, Gemüse und Teriyaki-Sauce.'),
            ('bowl', 'Hauptgericht', 'Vegetarische Buddha Bowl', 800, 'Bunte Schüssel mit verschiedenen Gemüsesorten, Tofu und einer hausgemachten Sauce.'),
            ('bowl', 'Hauptgericht', 'Poke Bowl', 700, 'Hawaiianische Schüssel mit rohem Fisch, Reis und verschiedenen Toppings.'),
            ('bowl', 'Hauptgericht', 'Ramen Suppe', 850, 'Japanische Nudelsuppe mit Brühe, Fleisch, Gemüse und Ei.'),
            ('bowl', 'Hauptgericht', 'Burrito Bowl', 780, 'Schüssel mit den Zutaten eines Burritos, aber ohne die Tortilla.'),
            ('bowl', 'Hauptgericht', 'Süßkartoffel Quinoa Bowl', 820, 'Schüssel mit gerösteter Süßkartoffel, Quinoa und verschiedenen Gemüsesorten.'),
            ('bowl', 'Hauptgericht', 'Couscous Gemüse Bowl', 750, 'Schüssel mit Couscous, gegrilltem Gemüse und einer leichten Dressing.'),
            ('bowl', 'Dessert', 'Matcha Cheesecake', 550, 'Cheesecake mit grünem Matcha-Tee für eine einzigartige Note.'),
            ('bowl', 'Dessert', 'Ananas Kokosnuss Sorbet', 600, 'Erfrischendes Sorbet mit dem Geschmack von Ananas und Kokosnuss.'),
            ('bowl', 'Getränk', 'Ingwer Limonade', 350, 'Erfrischende Limonade mit einem Hauch von Ingwer.'),
            ('bowl', 'Getränk', 'Aloe Vera Getränk', 350, 'Getränk mit Stücken von Aloe Vera, erfrischend und leicht süßlich.'),
            ('bowl', 'Getränk', 'Matcha Latte', 400, 'Milchgetränk mit grünem Matcha-Tee für einen cremigen und leicht herben Geschmack.'),
            ('bowl', 'Getränk', 'Chai Tee', 300, 'Würziger Tee mit einer Mischung aus Gewürzen wie Ingwer, Zimt und Nelken.'),
                   
            ('americasstory', 'Vorspeise', 'Nachos mit Guacamole', 600, 'Knusprige Tortilla-Chips mit würziger Guacamole.'),
            ('americasstory', 'Vorspeise', 'Chicken Wings', 650, 'Hähnchenflügel in verschiedenen Saucen, knusprig gebacken oder frittiert.'),
            ('americasstory', 'Vorspeise', 'Quesadillas', 550, 'Gefüllte Tortillas mit Käse und verschiedenen Toppings, serviert mit Dip.'),
            ('americasstory', 'Vorspeise', 'Spinat Artischocken Dip', 700, 'Cremiger Dip mit Spinat, Artischocken und Käse, dazu Brot oder Chips.'),
            ('americasstory', 'Hauptgericht', 'Burger "The American"', 800, 'Saftiger Burger mit den klassischen amerikanischen Belägen und Soßen.'),
            ('americasstory', 'Hauptgericht', 'BBQ Ribs', 850, 'Zarte Spareribs mit würziger BBQ-Sauce glasiert.'),
            ('americasstory', 'Hauptgericht', 'Mac n Cheese', 700, 'Nudeln mit cremiger Käsesauce, ein beliebtes amerikanisches Comfort Food.'),
            ('americasstory', 'Hauptgericht', 'Steak Tacos', 900, 'Tacos gefüllt mit saftigem Steak, Gemüse und Salsa.'),
            ('americasstory', 'Hauptgericht', 'Cajun Hähnchen', 780, 'Gewürztes und gegrilltes Hähnchen nach Cajun-Art.'),
            ('americasstory', 'Hauptgericht', 'Jambalaya', 820, 'Louisianisches Reisgericht mit einer Mischung aus Fleisch, Gemüse und Gewürzen.'),
            ('americasstory', 'Hauptgericht', 'Shrimp Po Boy Sandwich', 750, 'Sandwich mit frittierten Garnelen, Gemüse und Remoulade-Sauce.'),
            ('americasstory', 'Dessert', 'New York Cheesecake', 650, 'Klassischer cremiger Cheesecake aus New York.'),
            ('americasstory', 'Dessert', 'Pecan Pie', 700, 'Kuchen mit Pekannüssen und Sirupfüllung, serviert mit Schlagsahne.'),
            ('americasstory', 'Getränk', 'Root Beer', 350, 'Beliebtes amerikanisches Erfrischungsgetränk mit Wurzelaroma.'),
            ('americasstory', 'Getränk', 'Mint Julep', 400, 'Cocktail mit Minze, Bourbon, Zucker und Eis.'),
            ('americasstory', 'Getränk', 'Arnold Palmer', 300, 'Mischgetränk aus Eistee und Zitronenlimonade.'),
            ('americasstory', 'Getränk', 'Southern Sweet Tea', 350, 'Süßer Eistee, eine traditionelle Erfrischung im Süden der USA.'),
                    
            ('sidebysoups', 'Vorspeise', 'Tomatensuppe', 550, 'Klassische Tomatensuppe mit frischen Tomaten und Gewürzen.'),
            ('sidebysoups', 'Vorspeise', 'Minestrone', 600, 'Italienische Gemüsesuppe mit Nudeln oder Reis.'),
            ('sidebysoups', 'Vorspeise', 'Gazpacho', 500, 'Kalte spanische Gemüsesuppe mit Tomaten, Paprika und Gurken.'),
            ('sidebysoups', 'Vorspeise', 'Linsensuppe', 650, 'Herzhafte Linsensuppe mit Gemüse und Gewürzen.'),
            ('sidebysoups', 'Hauptgericht', 'Hühnersuppe', 750, 'Traditionelle Hühnersuppe mit zarten Hühnerstücken und Gemüse.'),
            ('sidebysoups', 'Hauptgericht', 'Ramen Suppe', 800, 'Japanische Nudelsuppe mit Brühe, Fleisch, Gemüse und Nudeln.'),
            ('sidebysoups', 'Hauptgericht', 'Pho', 700, 'Vietnamesische Nudelsuppe mit Rindfleisch oder Hühnchen.'),
            ('sidebysoups', 'Hauptgericht', 'Chowder', 850, 'Amerikanische Eintopfsuppe, oft mit Fisch oder Meeresfrüchten.'),
            ('sidebysoups', 'Hauptgericht', 'Gulaschsuppe', 780, 'Würzige Suppe mit Rindfleisch, Paprika und Kartoffeln.'),
            ('sidebysoups', 'Hauptgericht', 'Miso Ramen', 820, 'Japanische Ramen-Suppe mit Miso-Paste, Gemüse und Nudeln.'),
            ('sidebysoups', 'Hauptgericht', 'Kürbissuppe', 750, 'Cremige Kürbissuppe mit Gewürzen und Sahne.'),
            ('sidebysoups', 'Dessert', 'Schokoladenmousse', 550, 'Luftige Schokoladenmousse mit intensivem Schokoladengeschmack.'),
            ('sidebysoups', 'Dessert', 'Tiramisu', 600, 'Italienisches Dessert mit Löffelbiskuit, Kaffee und Mascarpone-Creme.'),
            ('sidebysoups', 'Getränk', 'Eistee', 350, 'Eistee, erfrischend und süß, perfekt für warme Tage.'),
            ('sidebysoups', 'Getränk', 'Frisch gepresster Saft', 400, 'Saft aus frischen Früchten, voller Vitamine und Geschmack.'),
            ('sidebysoups', 'Getränk', 'Ingwer-Zitronen-Tee', 300, 'Aufgebrühter Tee mit Ingwer und Zitrone, wohltuend und erfrischend.'),
            ('sidebysoups', 'Getränk', 'Gemüsesaft', 350, 'Saft aus verschiedenen Gemüsesorten, gesund und belebend.'),

            ('zoesgrill', 'Vorspeise', 'Falafel', 550, 'Kleine Bällchen aus pürierten Kichererbsen oder Bohnen, frittiert oder gebacken.'),
            ('zoesgrill', 'Vorspeise', 'Hummus mit Pitabrot', 600, 'Dip aus pürierten Kichererbsen, Tahini und Olivenöl, serviert mit Pitabrot.'),
            ('zoesgrill', 'Vorspeise', 'Baba Ganoush', 500, 'Dip aus gegrillter Aubergine, Knoblauch, Sesampaste und Olivenöl.'),
            ('zoesgrill', 'Vorspeise', 'Taboulé Salat', 650, 'Fruchtiger Salat aus Bulgur, Tomaten, Gurken, Minze und Petersilie.'),
            ('zoesgrill', 'Hauptgericht', 'Souvlaki Spieße', 750, 'Gegrillte Fleischspieße, oft mit Hühnchen oder Lamm, mariniert und gewürzt.'),
            ('zoesgrill', 'Hauptgericht', 'Moussaka', 800, 'Auflauf aus Auberginen, Hackfleisch und Bechamelsauce, griechische Spezialität.'),
            ('zoesgrill', 'Hauptgericht', 'Gyros Teller', 700, 'Griechisches Gericht mit gewürztem Fleisch, oft vom Drehspieß, serviert mit Beilagen.'),
            ('zoesgrill', 'Hauptgericht', 'Shawarma Wrap', 850, 'Gewürztes und gegrilltes Fleisch, oft Hähnchen oder Lamm, in einem Wrap.'),
            ('zoesgrill', 'Hauptgericht', 'Ratatouille', 780, 'Gemüseeintopf aus Auberginen, Zucchini, Paprika, Tomaten und Kräutern.'),
            ('zoesgrill', 'Hauptgericht', 'Linsen-Kofta Burger', 820, 'Burger-Patties aus Linsen, gewürzt und gebraten, serviert im Burger-Bun.'),
            ('zoesgrill', 'Hauptgericht', 'Gemüse-Satay Spieße', 750, 'Gegrillte Gemüsespieße mit würziger Erdnusssauce, asiatisch inspiriert.'),
            ('zoesgrill', 'Dessert', 'Baklava', 550, 'Süßes Gebäck aus Blätterteig, gefüllt mit Nüssen und mit Sirup getränkt.'),
            ('zoesgrill', 'Dessert', 'Loukoumades', 600, 'Griechische Donuts, frittiert und mit Honig oder Sirup beträufelt.'),
            ('zoesgrill', 'Getränk', 'Ouzo', 350, 'Anislikör aus Griechenland, traditionelles alkoholisches Getränk.'),
            ('zoesgrill', 'Getränk', 'Türkischer Kaffee', 400, 'Starke Kaffeespezialität, traditionell in der Türkei zubereitet.'),
            ('zoesgrill', 'Getränk', 'Ayran', 300, 'Erfrischendes Joghurtgetränk mit Wasser, Salz und manchmal Minze.'),
            ('zoesgrill', 'Getränk', 'Granatapfelsaft', 350, 'Fruchtiger Saft aus Granatäpfeln, gesund und erfrischend.'),
                   
            ('mcdaniels', 'Vorspeise', 'Chicken Nuggets', 550, 'Knusprig panierte Hühnchenstücke, perfekt zum Dippen in Saucen.'),
            ('mcdaniels', 'Vorspeise', 'Mozerella Sticks', 600, 'Käsestangen, paniert und frittiert, serviert mit Tomatensauce.'),
            ('mcdaniels', 'Vorspeise', 'Nachos mit Käsesauce', 500, 'Knusprige Tortillachips mit cremiger Käsesauce, ideal zum Teilen.'),
            ('mcdaniels', 'Vorspeise', 'Wings mit BBQ Sauce', 650, 'Hühnerflügel mit würziger BBQ-Sauce glasiert, lecker und saftig.'),
            ('mcdaniels', 'Hauptgericht', 'Big McD Burger', 750, 'Ein klassischer großer Burger mit Rindfleisch, frischem Gemüse und spezieller Sauce.'),
            ('mcdaniels', 'Hauptgericht', 'Crispy Chicken Burger', 800, 'Saftiges Hühnerfilet, paniert und frittiert, im Burger mit knackigem Gemüse.'),
            ('mcdaniels', 'Hauptgericht', 'Filet-O-Fish', 700, 'Fischfilet paniert und frittiert, im Burger mit Tartar-Sauce und Gurken.'),
            ('mcdaniels', 'Hauptgericht', 'McWrap Caesar', 850, 'Ein Wrap gefüllt mit gegrilltem Hühnchen, Parmesan, Tomaten und Caesar-Dressing.'),
            ('mcdaniels', 'Hauptgericht', 'McVeggie Burger', 780, 'Vegetarischer Burger mit einem Gemüsepatty, frischem Gemüse und spezieller Sauce.'),
            ('mcdaniels', 'Hauptgericht', 'McChicken', 820, 'Ein Klassiker mit paniertem Hühnchen, frischem Salat und Mayonnaise im Burger.'),
            ('mcdaniels', 'Hauptgericht', 'Double Cheeseburger', 750, 'Ein doppelter Genuss mit zwei Rindfleisch-Patties, Käse und Gemüse.'),
            ('mcdaniels', 'Dessert', 'Apfeltasche', 550, 'Süße Apfeltasche mit knusprigem Teig, gefüllt mit Zimt und Äpfeln.'),
            ('mcdaniels', 'Dessert', 'McFlurry mit Oreo', 600, 'Vanilleeis gemischt mit knusprigen Oreo-Keksen, ein leckeres Dessert.'),
            ('mcdaniels', 'Getränk', 'Cola', 350, 'Erfrischendes kohlensäurehaltiges Getränk.'),
            ('mcdaniels', 'Getränk', 'Eistee Pfirsich', 400, 'Eistee mit dem süßen Aroma von Pfirsich.'),
            ('mcdaniels', 'Getränk', 'Milchshake Erdbeere', 300, 'Cremiger Milchshake mit fruchtigem Erdbeergeschmack.'),
            ('mcdaniels', 'Getränk', 'Sprite', 350, 'Kohlensäurehaltiges Limonadengetränk mit Zitrusgeschmack.'),
                   
            ('subday', 'Vorspeise', 'Knoblauchbrot', 550, 'Geröstetes Brot mit intensivem Knoblauchgeschmack, perfekt als Vorspeise.'),
            ('subday', 'Vorspeise', 'Caprese Salat', 600, 'Klassischer italienischer Salat mit Tomaten, Mozzarella, Basilikum und Balsamico.'),
            ('subday', 'Vorspeise', 'Chicken Wings', 500, 'Knusprige Hühnerflügel, perfekt gewürzt und zum Dippen.'),
            ('subday', 'Vorspeise', 'Nachos mit Käse', 650, 'Knusprige Tortillachips mit geschmolzenem Käse, ideal zum Teilen.'),
            ('subday', 'Hauptgericht', 'Italian BMT Sub', 750, 'Sub-Sandwich mit verschiedenen italienischen Aufschnittsorten und Gemüse.'),
            ('subday', 'Hauptgericht', 'Chicken Teriyaki Sub', 800, 'Sub-Sandwich mit saftigem Hühnchen in Teriyaki-Sauce und frischem Gemüse.'),
            ('subday', 'Hauptgericht', 'Veggie Delight Sub', 700, 'Vegetarisches Sub-Sandwich mit einer Vielzahl von frischem Gemüse.'),
            ('subday', 'Hauptgericht', 'Tuna Sub', 850, 'Sub-Sandwich mit herzhaftem Thunfischsalat und frischem Gemüse.'),
            ('subday', 'Hauptgericht', 'Steak and Cheese Sub', 780, 'Sub-Sandwich mit saftigem Rindersteak, geschmolzenem Käse und Gemüse.'),
            ('subday', 'Hauptgericht', 'Turkey and Bacon Ranch Melt', 820, 'Sub-Sandwich mit Truthahn, knusprigem Bacon und cremigem Ranch-Dressing.'),
            ('subday', 'Hauptgericht', 'Spicy Italian Sub', 750, 'Würziges Sub-Sandwich mit verschiedenen italienischen Wurstsorten und scharfen Gewürzen.'),
            ('subday', 'Dessert', 'Chocolate Chip Cookie', 550, 'Klassisches Schokoladenkekse mit leckeren Schokoladenstücken.'),
            ('subday', 'Dessert', 'White Chocolate Macadamia Nut Cookie', 600, 'Keks mit weißer Schokolade und knackigen Macadamianüssen.'),
            ('subday', 'Getränk', 'Pepsi', 350, 'Kohlensäurehaltiges Erfrischungsgetränk.'),
            ('subday', 'Getränk', 'Mountain Dew', 400, 'Kohlensäurehaltiges Zitrusgetränk.'),
            ('subday', 'Getränk', 'Lipton Iced Tea', 300, 'Eistee von Lipton, erfrischend und leicht gesüßt.'),
            ('subday', 'Getränk', 'Aquafina Wasser', 350, 'Reines und erfrischendes Wasser von Aquafina.'),
                
            ('kfp', 'Vorspeise', 'Egg Rolls', 550, 'Knusprige Frühlingsrollen mit einer Füllung aus Gemüse und oft Fleisch.'),
            ('kfp', 'Vorspeise', 'Crab Rangoon', 600, 'Teigtaschen gefüllt mit Krabbenfleisch und Frischkäse, frittiert bis zur Perfektion.'),
            ('kfp', 'Vorspeise', 'Hot and Sour Suppe', 500, 'Würzige und saure Suppe mit Pilzen, Tofu, Eiern und Bambussprossen.'),
            ('kfp', 'Vorspeise', 'Edamame', 650, 'Gedämpfte junge Sojabohnenschoten, leicht gesalzen und als gesunder Snack serviert.'),
            ('kfp', 'Hauptgericht', 'General Tsos Chicken', 750, 'Knuspriges Hühnchen in süß-saurer Sauce mit einer leichten Schärfe, ein Klassiker.'),
            ('kfp', 'Hauptgericht', 'Sweet and Sour Pork', 800, 'Schweinefleisch in süß-saurer Sauce mit Ananas und Gemüse, köstlich abgeschmeckt.'),
            ('kfp', 'Hauptgericht', 'Beef and Broccoli', 700, 'Rindfleisch mit Brokkoli in würziger Sojasauce, einfach und dennoch lecker.'),
            ('kfp', 'Hauptgericht', 'Kung Pao Shrimp', 850, 'Garnelen gebraten mit Gemüse und Erdnüssen in einer würzigen Kung-Pao-Sauce.'),
            ('kfp', 'Hauptgericht', 'Vegetable Lo Mein', 780, 'Gebratene Nudeln mit einer Vielzahl von Gemüsesorten in Sojasauce.'),
            ('kfp', 'Hauptgericht', 'Mongolian Beef', 820, 'Rindfleisch in würziger Mongolen-Sauce, oft mit grünem Gemüse serviert.'),
            ('kfp', 'Hauptgericht', 'Szechuan Chicken', 750, 'Gebratenes Hühnchen mit Gemüse in würziger Szechuan-Sauce.'),
            ('kfp', 'Dessert', 'Fortune Cookies', 550, 'Knusprige Kekse mit einer darin versteckten Weisheit oder Prophezeiung.'),
            ('kfp', 'Dessert', 'Almond Cookies', 600, 'Kekse mit Mandelgeschmack, perfekt als süßer Abschluss.'),
            ('kfp', 'Getränk', 'Jasmin Tee', 350, 'Duftender Jasmin Tee, ein traditionelles chinesisches Getränk.'),
            ('kfp', 'Getränk', 'Lychee Limonade', 400, 'Erfrischende Limonade mit dem süßen Aroma von Lychee.'),
            ('kfp', 'Getränk', 'Plum Wine', 300, 'Süßer Pflaumenwein, eine beliebte alkoholische Spezialität in der asiatischen Küche.'),
            ('kfp', 'Getränk', 'Sake', 350, 'Japanischer Reiswein, kann kalt oder warm serviert werden.'),
                
            ('sunsetgrill', 'Vorspeise', 'Spinat-Artischocken-Dip', 550, 'Cremiger Dip aus Spinat, Artischocken und Käse, perfekt zum Eintauchen.'),
            ('sunsetgrill', 'Vorspeise', 'Mozzarella-Sticks', 600, 'Knusprige Sticks mit geschmolzenem Mozzarella, serviert mit Tomatensauce.'),
            ('sunsetgrill', 'Vorspeise', 'Chicken Quesadilla', 500, 'Gefüllte Tortilla mit Hühnchen, Käse und Gemüse, perfekt gegrillt.'),
            ('sunsetgrill', 'Vorspeise', 'Nachos Supreme', 650, 'Nachos mit herzhaften Belägen wie Fleisch, Käse, Jalapeños und Sour Cream.'),
            ('sunsetgrill', 'Hauptgericht', 'Sunset Burger', 750, 'Saftiger Burger mit den besten Belägen und hausgemachter Sauce.'),
            ('sunsetgrill', 'Hauptgericht', 'Ribeye-Steak', 800, 'Saftiges Ribeye-Steak, perfekt gegrillt und gewürzt nach Ihren Wünschen.'),
            ('sunsetgrill', 'Hauptgericht', 'Lachsfilet', 700, 'Gegrilltes Lachsfilet mit Kräutern und Zitrusaromen, leicht und lecker.'),
            ('sunsetgrill', 'Hauptgericht', 'Chicken Alfredo Pasta', 850, 'Nudeln mit cremiger Alfredo-Sauce, Hühnchen und Parmesan, ein Pasta-Klassiker.'),
            ('sunsetgrill', 'Hauptgericht', 'Vegetarische Fajitas', 780, 'Gegrilltes Gemüse mit Gewürzen, serviert mit Tortillas und Beilagen.'),
            ('sunsetgrill', 'Hauptgericht', 'Shrimp Scampi', 820, 'Gegrillte Garnelen in Knoblauchbutter und Zitronensauce, einfach und köstlich.'),
            ('sunsetgrill', 'Hauptgericht', 'BBQ Chicken Wrap', 750, 'Wrap gefüllt mit BBQ-Hühnchen, Gemüse und Sauce, perfekt für unterwegs.'),
            ('sunsetgrill', 'Dessert', 'New York Cheesecake', 550, 'Klassischer New York Cheesecake, cremig und mit Fruchtsauce.'),
            ('sunsetgrill', 'Dessert', 'Molten Chocolate Lava Cake', 600, 'Schokoladenkuchen mit flüssigem Kern, serviert mit Eis oder Sahne.'),
            ('sunsetgrill', 'Getränk', 'Mango Tango Smoothie', 350, 'Fruchtiger Smoothie mit süßer Mango und anderen köstlichen Früchten.'),
            ('sunsetgrill', 'Getränk', 'Pineapple Paradise', 400, 'Erfrischender Ananas-Paradies-Cocktail, ideal für tropische Geschmacksrichtungen.'),
            ('sunsetgrill', 'Getränk', 'Berry Burst Lemonade', 300, 'Zitronenlimonade mit gemischten Beeren, süß, sauer und erfrischend.'),
            ('sunsetgrill', 'Getränk', 'Iced Caramel Macchiato', 350, 'Eisgekühlter Karamell Macchiato, perfekte Mischung aus Kaffee und süßem Karamell.'),
                   
            ('fusiondelight', 'Vorspeise', 'Spring Rolls', 550, 'Frische Frühlingsrollen mit Gemüse und eventuell Fleisch, serviert mit Dip.'),
            ('fusiondelight', 'Vorspeise', 'Potstickers', 600, 'Teigtaschen gefüllt mit Fleisch oder Gemüse, gebraten bis knusprig.'),
            ('fusiondelight', 'Vorspeise', 'Seaweed Salad', 500, 'Salat aus Seetang, leicht gewürzt und oft mit Sesam garniert.'),
            ('fusiondelight', 'Vorspeise', 'Spicy Tuna Tartare', 650, 'Pikantes Thunfischtatar mit Gewürzen und Aromen, serviert meist auf Crackern.'),
            ('fusiondelight', 'Hauptgericht', 'Sushi Burrito', 750, 'Große Sushirolle in Burrito-Form, gefüllt mit Reis, Fisch, Gemüse und Saucen.'),
            ('fusiondelight', 'Hauptgericht', 'Bibimbap', 800, 'Koreanisches Gericht mit Reis, Gemüse, Fleisch und einem scharfen Gochujang-Sauce.'),
            ('fusiondelight', 'Hauptgericht', 'Pad Thai', 700, 'Gebratene Thai-Nudeln mit Garnelen, Hühnchen oder Tofu, Erdnüssen und Limette.'),
            ('fusiondelight', 'Hauptgericht', 'General Tsos Tofu', 850, 'Gebratenes Tofu in süß-saurer Sauce nach General Tso‘s Art.'),
            ('fusiondelight', 'Hauptgericht', 'Miso Glazed Salmon', 780, 'Lachs mit einer Glasur aus Miso-Marinade, gegrillt oder gebacken.'),
            ('fusiondelight', 'Hauptgericht', 'Teriyaki Chicken Bowl', 820, 'Hähnchen in Teriyaki-Sauce mit Reis und Gemüse, serviert in einer Schüssel.'),
            ('fusiondelight', 'Hauptgericht', 'Vegetarian Ramen', 750, 'Japanische Nudelsuppe mit Gemüse, Algen und einer würzigen Brühe.'),
            ('fusiondelight', 'Dessert', 'Matcha Green Tea Ice Cream', 550, 'Eiscreme mit dem intensiven Geschmack von Matcha-Grüntee.'),
            ('fusiondelight', 'Dessert', 'Mango Sticky Rice', 600, 'Klebreis mit frischer Mango, serviert mit süßer Kokosmilch.'),
            ('fusiondelight', 'Getränk', 'Bubble Tea', 350, 'Teegetränk mit Tapiokaperlen, oft in verschiedenen Geschmacksrichtungen.'),
            ('fusiondelight', 'Getränk', 'Lychee Mojito', 400, 'Erfrischender Mojito-Cocktail mit Lychee-Geschmack, Limette und Minze.'),
            ('fusiondelight', 'Getränk', 'Passion Fruit Iced Tea', 300, 'Eistee mit exotischem Geschmack von Passionsfrucht.'),
            ('fusiondelight', 'Getränk', 'Dragon Fruit Smoothie', 350, 'Fruchtiger Smoothie mit Drachenfrucht, Joghurt und Eis.'),
            
            ('spicynoodlehouse', 'Vorspeise', 'Edamame', 550, 'Junge Sojabohnen, gedämpft oder gekocht, mit Meersalz bestreut.'),
            ('spicynoodlehouse', 'Vorspeise', 'Spring Rolls', 600, 'Frühlingsrollen mit Gemüse, Kräutern und oft auch Fleisch, dazu Dip.'),
            ('spicynoodlehouse', 'Vorspeise', 'Kimchi', 500, 'Eingelegter und fermentierter Kohl, oft scharf gewürzt, koreanische Beilage.'),
            ('spicynoodlehouse', 'Vorspeise', 'Prawn Tempura', 650, 'Krosse, frittierte Garnelen in Tempurateig, serviert mit Dip.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Spicy Ramen', 750, 'Japanische Nudelsuppe mit würziger Brühe, Fleisch, Gemüse und Ei.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Dan Dan Noodles', 800, 'Chinesische Nudeln mit scharfer Erdnusssauce, Fleisch und Gemüse.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Szechuan Chicken', 700, 'Gebratenes Hühnchen in würziger Szechuan-Sauce mit Gemüse.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Shrimp Pad Thai', 850, 'Gebratene Thai-Nudeln mit Garnelen, Tamarindensauce und Erdnüssen.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Beef Bulgogi Udon', 780, 'Japanische Udon-Nudeln mit koreanisch mariniertem Rindfleisch.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Vegetarian Pho', 820, 'Vietnamesische Reisnudelsuppe mit Gemüse und Kräutern, vegetarisch.'),
            ('spicynoodlehouse', 'Hauptgericht', 'Kimchi Fried Rice', 750, 'Gebratener Reis mit Kimchi, Gemüse und je nach Wahl mit Fleisch.'),
            ('spicynoodlehouse', 'Dessert', 'Mango Sticky Rice', 550, 'Klebreis mit frischer Mango, serviert mit süßer Kokosmilch.'),
            ('spicynoodlehouse', 'Dessert', 'Green Tea Mochi', 600, 'Japanische Reiskuchen gefüllt mit grünem Tee Eiscreme.'),
            ('spicynoodlehouse', 'Getränk', 'Thai Iced Tea', 350, 'Eisgekühlter Schwarztee mit süßer Kondensmilch, typisch für Thailand.'),
            ('spicynoodlehouse', 'Getränk', 'Lemon Ginger Soda', 400, 'Erfrischendes Getränk mit Zitrone, Ingwer und Sprudelwasser.'),
            ('spicynoodlehouse', 'Getränk', 'Cucumber Mint Cooler', 300, 'Erfrischender Drink aus Gurke, Minze, Limettensaft und Soda.'),
            ('spicynoodlehouse', 'Getränk', 'Lychee Lemonade', 350, 'Limettenlimonade mit dem süßen Aroma von Lychee-Früchten.'),
            
            ('greenoasiscafe', 'Vorspeise', 'Caprese Salad', 550, 'Fruchtiger Salat mit Tomaten, Mozzarella und Basilikum, gewürzt mit Balsamico.'),
            ('greenoasiscafe', 'Vorspeise', 'Quinoa Stuffed Mushrooms', 600, 'Champignons gefüllt mit Quinoa, Gemüse und Gewürzen, gebacken oder gegrillt.'),
            ('greenoasiscafe', 'Vorspeise', 'Hummus Plate', 500, 'Geschmeidige Kichererbsenpaste mit Olivenöl, Knoblauch und Kräutern, serviert mit Brot.'),
            ('greenoasiscafe', 'Vorspeise', 'Bruschetta', 650, 'Geröstete Brotscheiben mit Tomaten, Knoblauch, Basilikum und Olivenöl.'),
            ('greenoasiscafe', 'Hauptgericht', 'Vegan Buddha Bowl', 750, 'Bunte Schüssel mit Gemüse, Getreide und Proteinen, oft mit Soße oder Dressing.'),
            ('greenoasiscafe', 'Hauptgericht', 'Avocado and Chickpea Wrap', 800, 'Wrap gefüllt mit Avocado, Kichererbsen, Gemüse und Dressing.'),
            ('greenoasiscafe', 'Hauptgericht', 'Mediterranean Quinoa Salad', 700, 'Quinoasalat mit mediterranem Gemüse, Oliven und Feta-Käse.'),
            ('greenoasiscafe', 'Hauptgericht', 'Pesto Zoodle Bowl', 850, 'Schüssel mit Zucchini-Nudeln, gewürzt mit Pesto und oft weiterem Gemüse.'),
            ('greenoasiscafe', 'Hauptgericht', 'Sweet Potato and Black Bean Tacos', 780, 'Tacos mit Süßkartoffeln, schwarzen Bohnen, Gemüse und Salsa.'),
            ('greenoasiscafe', 'Hauptgericht', 'Grilled Portobello Burger', 820, 'Gegrillter Portobello-Pilz als Burgerpatty, oft mit Gemüse und Sauce.'),
            ('greenoasiscafe', 'Hauptgericht', 'Soba Noodle Stir-Fry', 750, 'Japanisches Pfannengericht mit Soba-Nudeln, Gemüse und Sojasauce.'),
            ('greenoasiscafe', 'Dessert', 'Vegan Chocolate Cake', 550, 'Schokoladenkuchen ohne tierische Produkte, oft mit veganer Glasur.'),
            ('greenoasiscafe', 'Dessert', 'Coconut Milk Ice Cream', 600, 'Eiscreme auf Kokosmilchbasis, oft in verschiedenen exotischen Geschmacksrichtungen.'),
            ('greenoasiscafe', 'Getränk', 'Kale Pineapple Smoothie', 350, 'Smoothie mit Grünkohl, Ananas und weiteren Früchten, gesund und erfrischend.'),
            ('greenoasiscafe', 'Getränk', 'Cucumber Mint Detox Water', 400, 'Wasser mit Gurkenscheiben und Minze, erfrischend und entgiftend.'),
            ('greenoasiscafe', 'Getränk', 'Turmeric Latte', 300, 'Milchgetränk mit Kurkuma, Ingwer und Gewürzen, goldene Farbe, auch als "Goldene Milch" bekannt.'),
            ('greenoasiscafe', 'Getränk', 'Berry Blast Smoothie', 350, 'Fruchtiger Smoothie mit gemischten Beeren, oft mit Joghurt oder Saft zubereitet.'),
                   
            ('stellarsteaks', 'Vorspeise', 'Garlic Bread', 550, 'Knoblauchbrot, oft mit Butter bestrichen und im Ofen geröstet.'),
            ('stellarsteaks', 'Vorspeise', 'Shrimp Cocktail', 600, 'Garnelen serviert mit einer Cocktailsauce, oft auf Eis.'),
            ('stellarsteaks', 'Vorspeise', 'Mushroom Bruschetta', 500, 'Geröstetes Brot mit einer Mischung aus Pilzen, Tomaten, Knoblauch und Kräutern.'),
            ('stellarsteaks', 'Vorspeise', 'Caesar Salad', 650, 'Salat mit Römersalat, Croutons, Parmesan und Caesar-Dressing.'),
            ('stellarsteaks', 'Hauptgericht', 'Filet Mignon', 750, 'Zartes Rinderfilet, oft gegrillt oder gebraten, mit verschiedenen Beilagen.'),
            ('stellarsteaks', 'Hauptgericht', 'Ribeye Steak', 800, 'Saftiges Ribeye-Steak, oft gegrillt oder gebraten, mit intensivem Geschmack.'),
            ('stellarsteaks', 'Hauptgericht', 'Surf and Turf', 700, 'Kombination aus Fleisch (oft Rind) und Meeresfrüchten auf einem Teller.'),
            ('stellarsteaks', 'Hauptgericht', 'Lobster Tail', 850, 'Hummerschwanz, oft gegrillt oder gedämpft, mit Butter serviert.'),
            ('stellarsteaks', 'Hauptgericht', 'Salmon Steak', 780, 'Lachssteak, oft gegrillt oder gebraten, mit verschiedenen Beilagen.'),
            ('stellarsteaks', 'Hauptgericht', 'Chicken Marsala', 820, 'Hähnchenbrust in Marsala-Weinsauce, oft mit Pilzen.'),
            ('stellarsteaks', 'Hauptgericht', 'Vegetable Stir-Fry', 750, 'Gemüsepfanne, oft asiatisch gewürzt, in der Pfanne gebraten.'),
            ('stellarsteaks', 'Dessert', 'New York Cheesecake', 550, 'Klassischer Käsekuchen aus Frischkäse, Eiern und Zucker auf einem Keks- oder Kuchenboden.'),
            ('stellarsteaks', 'Dessert', 'Chocolate Lava Cake', 600, 'Schokoladenkuchen mit flüssigem Kern, oft mit Puderzucker bestäubt.'),
            ('stellarsteaks', 'Getränk', 'Red Wine', 350, 'Roter Wein, oft aus verschiedenen Rebsorten, in verschiedenen Geschmacksrichtungen.'),
            ('stellarsteaks', 'Getränk', 'White Wine', 400, 'Weißwein, oft aus verschiedenen Rebsorten, in verschiedenen Geschmacksrichtungen.'),
            ('stellarsteaks', 'Getränk', 'Old Fashioned', 300, 'Klassischer Cocktail mit Bourbon, Zucker, Wasser und Bitters, oft mit Orangenschale garniert.'),
            ('stellarsteaks', 'Getränk', 'Mint Julep', 350, 'Cocktail mit Bourbon, Minze, Zucker und Eis, oft in einem Silberbecher serviert.'),
                   
            ('thaiharmony', 'Vorspeise', 'Spring Rolls', 550, 'Frühlingsrollen, gefüllt mit Gemüse, Fleisch und Glasnudeln, oft frittiert.'),
            ('thaiharmony', 'Vorspeise', 'Tom Yum Soup', 600, 'Scharfe und saure Suppe mit Kräutern, Pilzen und oft Garnelen oder Hühnchen.'),
            ('thaiharmony', 'Vorspeise', 'Papaya Salad', 500, 'Salat aus grüner Papaya, Tomaten, Bohnen, Erdnüssen und Chili, oft mit Limettendressing.'),
            ('thaiharmony', 'Vorspeise', 'Chicken Satay', 650, 'Gegrillte Hühnerspieße, oft mit Erdnusssauce und Gurkensalat serviert.'),
            ('thaiharmony', 'Hauptgericht', 'Pad Thai', 750, 'Gebratene Nudeln mit Garnelen, Hühnchen oder Tofu, mit Erdnüssen und Limette garniert.'),
            ('thaiharmony', 'Hauptgericht', 'Green Curry', 800, 'Grünes Curry mit Kokosmilch, Gemüse und Fleisch oder Meeresfrüchten.'),
            ('thaiharmony', 'Hauptgericht', 'Massaman Beef', 700, 'Langsam gekochtes Rindfleisch in Massaman-Currysauce mit Kartoffeln und Erdnüssen.'),
            ('thaiharmony', 'Hauptgericht', 'Panang Chicken', 850, 'Panang Curry mit Hühnchen, cremig und würzig, oft mit Kaffir-Limettenblättern.'),
            ('thaiharmony', 'Hauptgericht', 'Basil Chicken Stir-Fry', 780, 'Gebratenes Hühnchen mit Basilikum, Chili, Knoblauch und Gemüse.'),
            ('thaiharmony', 'Hauptgericht', 'Pineapple Fried Rice', 820, 'Gebratener Reis mit Ananas, Gemüse, Hühnchen oder Garnelen, oft in einer Ananashälfte serviert.'),
            ('thaiharmony', 'Hauptgericht', 'Duck Red Curry', 750, 'Rotes Curry mit Ente, Kokosmilch, Bambussprossen und Thai-Auberginen.'),
            ('thaiharmony', 'Dessert', 'Mango Sticky Rice', 550, 'Klebreis mit frischer Mango, oft mit süßer Kokosmilch übergossen.'),
            ('thaiharmony', 'Dessert', 'Coconut Ice Cream', 600, 'Kokoseis, erfrischend und oft mit gerösteten Kokosnussflocken.'),
            ('thaiharmony', 'Getränk', 'Thai Iced Tea', 350, 'Eisgekühlter schwarzer Tee mit gezuckerter Kondensmilch, süß und erfrischend.'),
            ('thaiharmony', 'Getränk', 'Lychee Lemonade', 400, 'Erfrischende Limonade mit Lychee-Geschmack, oft mit frischen Lychee-Früchten.'),
            ('thaiharmony', 'Getränk', 'Tamarind Juice', 300, 'Saft aus Tamarinde, süß-sauer und erfrischend.'),
            ('thaiharmony', 'Getränk', 'Cucumber Mint Cooler', 350, 'Erfrischender Drink aus Gurke, Minze, Limette und Wasser.'),
                   
            ('cocoacraze', 'Vorspeise', 'Chocolate Covered Strawberries', 550, 'Erdbeeren mit Schokolade überzogen, eine süße Leckerei.'),
            ('cocoacraze', 'Vorspeise', 'Chocolate Truffle Bruschetta', 600, 'Geröstetes Brot mit Schokoladentrüffelbelag, eine luxuriöse Vorspeise.'),
            ('cocoacraze', 'Vorspeise', 'Caprese Skewers with Balsamic Chocolate Glaze', 500, 'Caprese-Spieße mit Schokoladen-Balsamico-Glasur, eine einzigartige Kombination.'),
            ('cocoacraze', 'Vorspeise', 'Chocolate Fondue with Fresh Fruit', 650, 'Schokoladenfondue mit frischem Obst, perfekt zum Eintauchen.'),
            ('cocoacraze', 'Hauptgericht', 'Mole Chicken Enchiladas', 750, 'Enchiladas mit Mole-Hühnchenfüllung, reichhaltig und würzig.'),
            ('cocoacraze', 'Hauptgericht', 'Cocoa Rubbed BBQ Ribs', 800, 'BBQ-Rippchen mit Kakao gewürzt, eine interessante Geschmackskombination.'),
            ('cocoacraze', 'Hauptgericht', 'Chocolate Chili Con Carne', 700, 'Chili con Carne mit Schokolade, herzhaft und leicht süßlich.'),
            ('cocoacraze', 'Hauptgericht', 'Cocoa Spiced Salmon', 850, 'Lachs mit Kakao gewürzt, eine delikate und ungewöhnliche Zubereitung.'),
            ('cocoacraze', 'Hauptgericht', 'Chocolate Infused Penne Pasta', 780, 'Penne Pasta mit Schokoladenaroma, eine kreative Pasta-Variation.'),
            ('cocoacraze', 'Hauptgericht', 'Cocoa Dusted Shrimp Scampi', 820, 'Shrimp Scampi mit Kakao bestäubt, ein exotisches Meeresfrüchtegericht.'),
            ('cocoacraze', 'Hauptgericht', 'Chocolate Risotto', 750, 'Risotto mit Schokolade verfeinert, cremig und geschmacksintensiv.'),
            ('cocoacraze', 'Dessert', 'Dark Chocolate Mousse', 550, 'Mousse aus dunkler Schokolade, luftig und intensiv im Geschmack.'),
            ('cocoacraze', 'Dessert', 'White Chocolate Raspberry Cheesecake', 600, 'Käsekuchen mit Himbeerfüllung, getoppt mit weißer Schokolade.'),
            ('cocoacraze', 'Getränk', 'Chocolate Martini', 350, 'Martini mit Schokoladenlikör, ein köstlicher Cocktail.'),
            ('cocoacraze', 'Getränk', 'Mint Chocolate Shake', 400, 'Milchshake mit Minze und Schokolade, erfrischend und lecker.'),
            ('cocoacraze', 'Getränk', 'Chocolate Mint Iced Coffee', 300, 'Eiskaffee mit Schokoladenminzgeschmack, eine aromatische Kaffeevariation.'),
            ('cocoacraze', 'Getränk', 'Hazelnut Hot Chocolate', 350, 'Heiße Schokolade mit Haselnussgeschmack, ein wärmender Genuss.'),
                   
            ('mysticalmezze', 'Vorspeise', 'Hummus with Pita Bread', 550, 'Creamy hummus served with soft pita bread, a classic and flavorful starter.'),
            ('mysticalmezze', 'Vorspeise', 'Baba Ganoush', 600, 'Smoky eggplant dip made with tahini, garlic, and olive oil, perfect for dipping.'),
            ('mysticalmezze', 'Vorspeise', 'Falafel', 500, 'Crispy and savory chickpea fritters, a popular and satisfying choice.'),
            ('mysticalmezze', 'Vorspeise', 'Stuffed Grape Leaves', 650, 'Grape leaves filled with a seasoned mixture of rice and herbs, a delightful appetizer.'),
            ('mysticalmezze', 'Hauptgericht', 'Shawarma Plate', 750, 'Tender and flavorful shawarma served as a hearty plate with accompaniments.'),
            ('mysticalmezze', 'Hauptgericht', 'Moussaka', 800, 'Layered casserole with eggplant, minced meat, and béchamel sauce, a Greek specialty.'),
            ('mysticalmezze', 'Hauptgericht', 'Vegetarian Kebab', 700, 'Grilled skewers with assorted vegetables, a delicious meatless option.'),
            ('mysticalmezze', 'Hauptgericht', 'Lentil Soup', 850, 'Hearty soup made with lentils, vegetables, and aromatic spices, a comforting choice.'),
            ('mysticalmezze', 'Hauptgericht', 'Greek Salad', 780, 'Fresh salad with tomatoes, cucumbers, olives, and feta cheese, a light and refreshing dish.'),
            ('mysticalmezze', 'Hauptgericht', 'Chicken Souvlaki Wrap', 820, 'Grilled chicken souvlaki wrapped in pita bread, a portable and flavorful option.'),
            ('mysticalmezze', 'Hauptgericht', 'Spinach and Feta Pie', 750, 'Savory pie filled with spinach and feta cheese, a delightful vegetarian choice.'),
            ('mysticalmezze', 'Dessert', 'Baklava', 550, 'Sweet pastry made of layers of phyllo dough, filled with nuts and honey.'),
            ('mysticalmezze', 'Dessert', 'Greek Yogurt with Honey and Walnuts', 600, 'Creamy Greek yogurt topped with honey and walnuts, a simple and satisfying dessert.'),
            ('mysticalmezze', 'Getränk', 'Ouzo', 350, 'Anise-flavored liquor from Greece, a traditional and strong alcoholic beverage.'),
            ('mysticalmezze', 'Getränk', 'Tzatziki Smoothie', 400, 'Refreshing smoothie with cucumber, yogurt, and mint, a cool and tangy drink.'),
            ('mysticalmezze', 'Getränk', 'Mint Lemonade', 300, 'Lemonade infused with fresh mint, a crisp and revitalizing beverage.'),
            ('mysticalmezze', 'Getränk', 'Cucumber Greek Yogurt Drink', 350, 'Cooling drink with cucumber and Greek yogurt, a traditional and hydrating option.'),
                   
        ('saffronspice', 'Vorspeise', 'Safran-Suppe', 650, 'Aromatische Suppe mit Safran, eine delikate Vorspeise.'),
        ('saffronspice', 'Vorspeise', 'Safran-Marinierte Garnelen', 700, 'Garnelen mariniert in Safran, perfekt gewürzt und gebraten.'),
        ('saffronspice', 'Vorspeise', 'Gebratene Safran-Champignons', 600, 'Champignons in Safran gebraten, ein köstlicher Start.'),
        ('saffronspice', 'Vorspeise', 'Safran-Honig-Glasierte Hähnchenflügel', 750, 'Hähnchenflügel glasiert mit einer Mischung aus Safran und Honig.'),
        ('saffronspice', 'Hauptgericht', 'Safran-Hühnchen-Curry', 850, 'Hühnchencurry mit intensivem Safranaroma, reichhaltig und würzig.'),
        ('saffronspice', 'Hauptgericht', 'Safran-Gewürzreis mit Gemüse', 800, 'Würziger Reis mit Safran und Gemüse, eine aromatische Beilage.'),
        ('saffronspice', 'Hauptgericht', 'Lammragout mit Safransauce', 900, 'Zartes Lammragout in einer köstlichen Safransauce.'),
        ('saffronspice', 'Hauptgericht', 'Safran-Zitronen-Hähnchen', 820, 'Hähnchen mit einer erfrischenden Safran-Zitronen-Marinade.'),
        ('saffronspice', 'Hauptgericht', 'Safran-Fisch mit Kartoffeln', 780, 'Gebratener Fisch mit Safran und Kartoffeln, ein Genuss für Meeresfrüchte-Liebhaber.'),
        ('saffronspice', 'Hauptgericht', 'Gemischte Pilaf mit Safran', 830, 'Safran-Pilaf mit einer Mischung aus verschiedenen Aromen.'),
        ('saffronspice', 'Dessert', 'Safran-Pistazien-Eis', 500, 'Erfrischendes Eis mit Safran und Pistazien, eine einzigartige Nachspeise.'),
        ('saffronspice', 'Dessert', 'Safran-Zuckerplätzchen', 550, 'Zarte Zuckerplätzchen mit einem Hauch von Safran.'),
        ('saffronspice', 'Getränk', 'Safran-Rosmarin-Limonade', 350, 'Erfrischende Limonade mit Safran und Rosmarin.'),
        ('saffronspice', 'Getränk', 'Safran-Minztee', 400, 'Wohltuender Minztee mit einer Note von Safran.'),
        ('saffronspice', 'Getränk', 'Safran-Ingwer-Smoothie', 300, 'Gesunder Smoothie mit Safran und Ingwer.'),
        ('saffronspice', 'Getränk', 'Safran-Kardamom-Latte', 380, 'Wärmender Latte mit Safran und Kardamom.'),
                   
        ('tropicaltaco', 'Vorspeise', 'Mango-Salsa mit Avocado', 650, 'Fruchtige Salsa mit reifer Mango und cremiger Avocado.'),
        ('tropicaltaco', 'Vorspeise', 'Ananas-Guacamole', 700, 'Guacamole mit frischer Ananas, eine exotische Variation.'),
        ('tropicaltaco', 'Vorspeise', 'Tropischer Meeresfrüchtesalat', 600, 'Salat mit Meeresfrüchten und tropischen Aromen.'),
        ('tropicaltaco', 'Vorspeise', 'Kokos-Limetten-Garnelen', 750, 'Garnelen in Kokos-Limetten-Sauce, köstlich mariniert.'),
        ('tropicaltaco', 'Hauptgericht', 'Tropischer Fisch-Taco', 850, 'Taco mit frischem Fisch und exotischen Zutaten.'),
        ('tropicaltaco', 'Hauptgericht', 'Karibische Hähnchen-Enchiladas', 800, 'Enchiladas mit karibischem Hähnchen, würzig und lecker.'),
        ('tropicaltaco', 'Hauptgericht', 'Guave-Glasierter Schweinebauch', 900, 'Saftiger Schweinebauch mit süßer Guaven-Glasur.'),
        ('tropicaltaco', 'Hauptgericht', 'Mango-Chili-Hühnchen', 820, 'Hähnchen mit einer feurigen Mango-Chili-Sauce.'),
        ('tropicaltaco', 'Hauptgericht', 'Tropischer Gemüseburrito', 780, 'Burrito gefüllt mit tropischem Gemüse und Reis.'),
        ('tropicaltaco', 'Hauptgericht', 'Ananas-Rindfleisch-Tostadas', 830, 'Tostadas mit saftigem Rindfleisch und frischer Ananas.'),
        ('tropicaltaco', 'Dessert', 'Kokos-Ananas-Sorbet', 500, 'Erfrischendes Sorbet mit Kokosnuss und Ananas.'),
        ('tropicaltaco', 'Dessert', 'Passionsfrucht-Tiramisu', 550, 'Tiramisu mit dem exotischen Geschmack von Passionsfrucht.'),
        ('tropicaltaco', 'Getränk', 'Guaven-Limetten-Margarita', 350, 'Margarita mit dem süßen Aroma von Guave und frischer Limette.'),
        ('tropicaltaco', 'Getränk', 'Kokosnuss-Pina-Colada', 400, 'Klassischer Pina Colada mit cremiger Kokosnuss.'),
        ('tropicaltaco', 'Getränk', 'Mango-Chili-Mojito', 300, 'Erfrischender Mojito mit Mango und einem Hauch von Chili.'),
        ('tropicaltaco', 'Getränk', 'Tropischer Fruchtshake', 380, 'Fruchtiger Shake mit einer Mischung tropischer Früchte.'),
                   
        ('zwiebelzirkus', 'Vorspeise', 'Zwiebelringe mit Chili-Dip', 650, 'Knusprige Zwiebelringe mit würzigem Chili-Dip.'),
        ('zwiebelzirkus', 'Vorspeise', 'Zwiebelsuppe mit Käsecroutons', 700, 'Herzhafte Zwiebelsuppe mit Käsecroutons.'),
        ('zwiebelzirkus', 'Vorspeise', 'Zwiebel-Balsamico-Bruschetta', 600, 'Geröstetes Brot mit Zwiebeln und Balsamico-Glasur.'),
        ('zwiebelzirkus', 'Vorspeise', 'Zwiebel-Kartoffel-Puffer', 750, 'Knusprige Puffer aus Zwiebeln und Kartoffeln.'),
        ('zwiebelzirkus', 'Hauptgericht', 'Zwiebelrostbraten', 850, 'Saftiger Rostbraten mit geschmorten Zwiebeln.'),
        ('zwiebelzirkus', 'Hauptgericht', 'Gefüllte Zwiebeln mit Hackfleisch', 800, 'Zwiebeln gefüllt mit herzhaftem Hackfleisch.'),
        ('zwiebelzirkus', 'Hauptgericht', 'Zwiebel-Quiche', 900, 'Flan mit einer Füllung aus Zwiebeln und weiteren Zutaten.'),
        ('zwiebelzirkus', 'Hauptgericht', 'Zwiebel-Honig-Hähnchen', 820, 'Zartes Hähnchen in einer süß-würzigen Zwiebel-Honig-Sauce.'),
        ('zwiebelzirkus', 'Hauptgericht', 'Zwiebel-Kartoffel-Gratin', 780, 'Überbackenes Gratin mit Zwiebeln und Kartoffeln.'),
        ('zwiebelzirkus', 'Hauptgericht', 'Zwiebel-Maultaschen', 830, 'Gefüllte Teigtaschen mit einer herzhaften Zwiebelfüllung.'),
        ('zwiebelzirkus', 'Dessert', 'Zwiebel-Tarte Tatin', 500, 'Süße Tarte Tatin mit karamellisierten Zwiebeln.'),
        ('zwiebelzirkus', 'Dessert', 'Zwiebel-Schokoladenkuchen', 550, 'Schokoladenkuchen mit einer besonderen Zwiebelnote.'),
        ('zwiebelzirkus', 'Getränk', 'Zwiebel-Limonade', 350, 'Erfrischende Limonade mit einem Hauch von Zwiebel.'),
        ('zwiebelzirkus', 'Getränk', 'Zwiebel-Ingwer-Tee', 400, 'Aufwärmender Tee mit Zwiebeln und Ingwer.'),
        ('zwiebelzirkus', 'Getränk', 'Zwiebel-Minz-Smoothie', 300, 'Gesunder Smoothie mit Minze und frischen Zwiebeln.'),
        ('zwiebelzirkus', 'Getränk', 'Zwiebel-Bier', 380, 'Bier mit einer einzigartigen Zwiebelnote.'),
                   
        ('wurstundsenf', 'Vorspeise', 'Weißwurst mit süßem Senf', 650, 'Traditionelle Weißwurst mit süßem Senf serviert.'),
        ('wurstundsenf', 'Vorspeise', 'Currywurst mit Pommes', 700, 'Currywurst mit knusprigen Pommes und würziger Sauce.'),
        ('wurstundsenf', 'Vorspeise', 'Leberkäse-Semmel', 600, 'Saftiger Leberkäse in einer Semmel serviert.'),
        ('wurstundsenf', 'Vorspeise', 'Senf-Eingelegte Bratwurst', 750, 'Bratwurst eingelegt in aromatischem Senf.'),
        ('wurstundsenf', 'Hauptgericht', 'Thüringer Rostbratwurst', 850, 'Herzhafte Thüringer Rostbratwurst.'),
        ('wurstundsenf', 'Hauptgericht', 'Debrecziner mit Sauerkraut', 800, 'Würzige Debrecziner mit saftigem Sauerkraut.'),
        ('wurstundsenf', 'Hauptgericht', 'Bockwurst mit Kartoffelsalat', 900, 'Zarte Bockwurst mit hausgemachtem Kartoffelsalat.'),
        ('wurstundsenf', 'Hauptgericht', 'Weißwurst-Gulasch', 820, 'Gulasch mit zarten Weißwurststücken.'),
        ('wurstundsenf', 'Hauptgericht', 'Nürnberger Rostbratwurst', 780, 'Kleine, würzige Nürnberger Rostbratwurst.'),
        ('wurstundsenf', 'Hauptgericht', 'Senf-Sauerbraten', 830, 'Sauerbraten mit einer besonderen Senfnote.'),
        ('wurstundsenf', 'Dessert', 'Senf-Eis mit Brezelstückchen', 500, 'Erfrischendes Senf-Eis mit knusprigen Brezelstückchen.'),
        ('wurstundsenf', 'Dessert', 'Senf-Honig-Pudding', 550, 'Leckerer Honigpudding mit einem Hauch von Senf.'),
        ('wurstundsenf', 'Getränk', 'Senf-Radler', 350, 'Erfrischendes Radler mit einem Spritzer Senf.'),
        ('wurstundsenf', 'Getränk', 'Weißbier mit Senf', 400, 'Klassisches Weißbier mit einer Prise Senf.'),
        ('wurstundsenf', 'Getränk', 'Senf-Limonade', 300, 'Erfrischende Limonade mit einer leichten Senfnote.'),
        ('wurstundsenf', 'Getränk', 'Senf-Cocktail', 380, 'Cocktail mit einer einzigartigen Senf-Würze.'),
        
        ('rheinweinhaus', 'Vorspeise', 'Käseplatte mit Trauben', 650, 'Auswahl an verschiedenen Käsesorten mit frischen Trauben.'),
        ('rheinweinhaus', 'Vorspeise', 'Rheinischer Sauerbraten-Salat', 700, 'Salat mit zartem Rheinischen Sauerbraten.'),
        ('rheinweinhaus', 'Vorspeise', 'Zwiebelkuchen mit Speck', 600, 'Herzhafter Zwiebelkuchen mit knusprigem Speck.'),
        ('rheinweinhaus', 'Vorspeise', 'Obatzda mit Brezel', 750, 'Cremiger Obatzda-Dip mit frischer Brezel.'),
        ('rheinweinhaus', 'Hauptgericht', 'Rheinischer Sauerbraten mit Knödeln', 850, 'Traditioneller Sauerbraten mit Kartoffelknödeln.'),
        ('rheinweinhaus', 'Hauptgericht', 'Weinblatt-Gefüllte Forelle', 800, 'Forelle gefüllt mit Weinblättern und aromatischen Gewürzen.'),
        ('rheinweinhaus', 'Hauptgericht', 'Riesling-Hähnchen mit Spargel', 900, 'Hähnchen in Rieslingsauce mit frischem Spargel.'),
        ('rheinweinhaus', 'Hauptgericht', 'Zanderfilet in Rieslingsoße', 820, 'Zarter Zander in einer delikaten Rieslingsoße.'),
        ('rheinweinhaus', 'Hauptgericht', 'Schweinshaxe mit Sauerkraut', 780, 'Knusprige Schweinshaxe mit deftigem Sauerkraut.'),
        ('rheinweinhaus', 'Hauptgericht', 'Rheinischer Zwiebelkuchen', 830, 'Klassischer Zwiebelkuchen nach Rheinischer Art.'),
        ('rheinweinhaus', 'Dessert', 'Rheinischer Apfelstrudel', 500, 'Hausgemachter Apfelstrudel nach Rheinischer Rezeptur.'),
        ('rheinweinhaus', 'Dessert', 'Trauben-Mascarpone-Dessert', 550, 'Dessert mit Trauben und cremigem Mascarpone.'),
        ('rheinweinhaus', 'Getränk', 'Rheinischer Riesling', 350, 'Erfrischender Rheinischer Riesling-Wein.'),
        ('rheinweinhaus', 'Getränk', 'Gewürztraminer Spritzer', 400, 'Erfrischender Spritzer mit Gewürztraminer-Wein.'),
        ('rheinweinhaus', 'Getränk', 'Rheinischer Rotwein', 300, 'Kräftiger Rheinischer Rotwein.'),
        ('rheinweinhaus', 'Getränk', 'Rheinischer Winzersekt', 380, 'Edler Winzersekt aus der Rheinregion.'),
                   
        ('schwarzbrotstube', 'Vorspeise', 'Laugenbrezel mit Obatzda', 650, 'Frische Laugenbrezel mit cremigem Obatzda-Dip.'),
        ('schwarzbrotstube', 'Vorspeise', 'Roggenbrot mit Leberwurst', 700, 'Herzhaftes Roggenbrot mit würziger Leberwurst.'),
        ('schwarzbrotstube', 'Vorspeise', 'Bauernbrot mit Griebenschmalz', 600, 'Kräftiges Bauernbrot mit Griebenschmalz.'),
        ('schwarzbrotstube', 'Vorspeise', 'Kartoffelsuppe mit Schwarzbrot-Croutons', 750, 'Kartoffelsuppe mit knusprigen Schwarzbrot-Croutons.'),
        ('schwarzbrotstube', 'Hauptgericht', 'Sauerbraten mit Kartoffelknödeln', 850, 'Traditioneller Sauerbraten mit Kartoffelknödeln.'),
        ('schwarzbrotstube', 'Hauptgericht', 'Rinderrouladen mit Schwarzbrotfüllung', 800, 'Rinderrouladen gefüllt mit herzhafter Schwarzbrotmischung.'),
        ('schwarzbrotstube', 'Hauptgericht', 'Kartoffel-Gemüse-Auflauf mit Kräuterquark', 900, 'Vegetarischer Auflauf mit Kartoffeln, Gemüse und Kräuterquark.'),
        ('schwarzbrotstube', 'Hauptgericht', 'Kohlrouladen mit Schwarzbrotsoße', 820, 'Kohlrouladen in deftiger Schwarzbrotsoße.'),
        ('schwarzbrotstube', 'Hauptgericht', 'Schweinebraten mit Schwarzbrotkruste', 780, 'Saftiger Schweinebraten mit knuspriger Schwarzbrotkruste.'),
        ('schwarzbrotstube', 'Hauptgericht', 'Kartoffelsalat mit Schwarzbrotcroutons', 830, 'Klassischer Kartoffelsalat mit knusprigen Schwarzbrotcroutons.'),
        ('schwarzbrotstube', 'Dessert', 'Schwarzbrot-Eis mit Kirschsoße', 500, 'Erfrischendes Eis mit Schwarzbrotstücken und Kirschsoße.'),
        ('schwarzbrotstube', 'Dessert', 'Pumpernickel-Mousse', 550, 'Luftiges Mousse mit aromatischem Pumpernickel.'),
        ('schwarzbrotstube', 'Getränk', 'Schwarzbrot-Smoothie', 350, 'Gesunder Smoothie mit Schwarzbrot und frischem Obst.'),
        ('schwarzbrotstube', 'Getränk', 'Kümmel-Kwas', 400, 'Erfrischendes Getränk mit Schwarzbrot und Kümmel.'),
        ('schwarzbrotstube', 'Getränk', 'Schwarzbrot-Kaffee', 300, 'Kaffee mit einem Hauch von Schwarzbrotaroma.'),
        ('schwarzbrotstube', 'Getränk', 'Malzbier', 380, 'Malzbier mit malziger Note und erfrischendem Geschmack.'),
                   
        ('pilzparadies', 'Vorspeise', 'Champignon-Crostini', 550, 'Geröstete Crostini mit frischen Champignons.'),
        ('pilzparadies', 'Vorspeise', 'Gebratene Pfifferlinge in Knoblauchbutter', 600, 'Pfifferlinge sautiert in Knoblauchbutter.'),
        ('pilzparadies', 'Vorspeise', 'Pilz-Carpaccio mit Parmesan', 500, 'Fein geschnittene Pilzscheiben mit Parmesan.'),
        ('pilzparadies', 'Vorspeise', 'Gefüllte Shiitake-Pilze', 650, 'Shiitake-Pilze gefüllt mit würziger Füllung.'),
        ('pilzparadies', 'Hauptgericht', 'Pilzrisotto mit Trüffelöl', 750, 'Risotto zubereitet mit verschiedenen Pilzsorten und Trüffelöl.'),
        ('pilzparadies', 'Hauptgericht', 'Gefüllte Portobello-Pilze mit Spinat und Feta', 800, 'Portobello-Pilze gefüllt mit Spinat und Feta-Käse.'),
        ('pilzparadies', 'Hauptgericht', 'Pilz-Gnocchi mit Salbei-Butter', 700, 'Gnocchi mit Pilzen in einer würzigen Salbei-Butter-Sauce.'),
        ('pilzparadies', 'Hauptgericht', 'Steinpilz-Ravioli mit Pilzrahmsauce', 850, 'Hausgemachte Ravioli gefüllt mit Steinpilzen in Pilzrahmsauce.'),
        ('pilzparadies', 'Hauptgericht', 'Pfifferlinge in Rahmsauce mit Semmelknödel', 780, 'Pfifferlinge in cremiger Rahmsauce mit hausgemachten Semmelknödeln.'),
        ('pilzparadies', 'Dessert', 'Pilz-Tiramisu', 600, 'Ein einzigartiges Tiramisu mit Pilznote.'),
        ('pilzparadies', 'Dessert', 'Pilz-Schokoladenmousse', 650, 'Schokoladenmousse mit subtilem Pilzaroma.'),
        ('pilzparadies', 'Getränk', 'Pilz-Cocktail', 350, 'Erfrischender Cocktail mit Pilzinfusion.'),
        ('pilzparadies', 'Getränk', 'Pilz-Minz-Smoothie', 400, 'Gesunder Smoothie mit Pilzen und frischer Minze.'),
        ('pilzparadies', 'Getränk', 'Pilz-Ingwer-Limonade', 300, 'Limonade mit Pilzen und einem Hauch von Ingwer.'),
        ('pilzparadies', 'Getränk', 'Pilz-Latte', 350, 'Warmer Latte mit Pilzgeschmack.'),
                   
        ('sauerkrautundwurst', 'Vorspeise', 'Sauerkrautbällchen mit Senf-Dip', 550, 'Knusprig frittierte Bällchen aus Sauerkraut mit einem Dip aus verschiedenen Senfsorten.'),
        ('sauerkrautundwurst', 'Vorspeise', 'Wurstplatte mit verschiedenen Senfsorten', 600, 'Auswahl an Wurstsorten mit einer Vielzahl von Senfsorten.'),
        ('sauerkrautundwurst', 'Vorspeise', 'Sauerkraut-Rouladen mit Hackfleisch', 500, 'Sauerkraut-Rouladen gefüllt mit herzhaftem Hackfleisch.'),
        ('sauerkrautundwurst', 'Vorspeise', 'Sauerkrautsuppe mit Mettwurst', 650, 'Herzhafte Suppe mit Sauerkraut und Mettwurst.'),
        ('sauerkrautundwurst', 'Hauptgericht', 'Weisswurst mit Brezn und süßem Senf', 700, 'Traditionelle Weisswurst mit Brezn und süßem Senf.'),
        ('sauerkrautundwurst', 'Hauptgericht', 'Thüringer Rostbratwurst mit Sauerkraut', 800, 'Thüringer Rostbratwurst serviert mit Sauerkraut.'),
        ('sauerkrautundwurst', 'Hauptgericht', 'Hackbraten mit Sauerkraut und Kartoffelpüree', 750, 'Saftiger Hackbraten mit Beilage von Sauerkraut und Kartoffelpüree.'),
        ('sauerkrautundwurst', 'Hauptgericht', 'Wurstgulasch mit Sauerkrautnockerln', 850, 'Gulasch aus verschiedenen Wurstsorten mit Beilage von Sauerkrautnockerln.'),
        ('sauerkrautundwurst', 'Hauptgericht', 'Kasseler mit Sauerkraut und Kartoffelsalat', 780, 'Geräuchertes Kasseler mit Beilagen von Sauerkraut und Kartoffelsalat.'),
        ('sauerkrautundwurst', 'Dessert', 'Sauerkrautstrudel mit Vanillesauce', 600, 'Strudel gefüllt mit süßem Sauerkraut, serviert mit Vanillesauce.'),
        ('sauerkrautundwurst', 'Dessert', 'Senf-Eis mit Sauerkraut-Chips', 650, 'Erfrischendes Senf-Eis garniert mit knusprigen Sauerkraut-Chips.'),
        ('sauerkrautundwurst', 'Getränk', 'Sauerkraut-Smoothie', 350, 'Gesunder Smoothie mit Sauerkraut und frischem Gemüse.'),
        ('sauerkrautundwurst', 'Getränk', 'Wurst-Wodka', 400, 'Cocktail mit Wurstinfusion und Wodka.'),
        ('sauerkrautundwurst', 'Getränk', 'Senf-Mule', 300, 'Erfrischender Mule-Cocktail mit einer besonderen Senf-Note.'),
        ('sauerkrautundwurst', 'Getränk', 'Sauerkrautsaft', 350, 'Natürlicher Saft aus fermentiertem Sauerkraut.'),
                   
        ('cafebluerose', 'Vorspeise', 'Himbeer-Mandel-Cupcakes', 350, 'Leckere Himbeer-Mandel-Cupcakes für einen süßen Start.'),
        ('cafebluerose', 'Vorspeise', 'Vanille-Blumenkohl-Muffins', 300, 'Ungewöhnlich leckere Muffins mit einer Prise Vanille und Blumenkohl.'),
        ('cafebluerose', 'Vorspeise', 'Zitronen-Poppyseed-Scones', 400, 'Fruchtige Zitronen-Scones mit Mohnsamen für einen erfrischenden Genuss.'),
        ('cafebluerose', 'Vorspeise', 'Schokoladen-Chia-Pudding', 450, 'Gesunder Schokoladen-Chia-Pudding, perfekt als Snack oder Dessert.'),
        ('cafebluerose', 'Hauptgericht', 'Apfel-Zimt-Pfannkuchen', 550, 'Luftige Pfannkuchen mit frischen Äpfeln und einer Prise Zimt.'),
        ('cafebluerose', 'Hauptgericht', 'Blumenkohl-Walnuss-Waffeln', 500, 'Herzhafte Waffeln mit Blumenkohl und knackigen Walnüssen.'),
        ('cafebluerose', 'Hauptgericht', 'Himbeer-Mandel-French-Toast', 600, 'French Toast mit einem Hauch von Himbeeren und Mandeln.'),
        ('cafebluerose', 'Hauptgericht', 'Erdbeer-Bananen-Smoothie-Bowl', 650, 'Gesunde Smoothie-Bowl mit frischen Erdbeeren und Bananen.'),
        ('cafebluerose', 'Dessert', 'Blue Rose Schokoladenkuchen', 700, 'Verwöhnen Sie Ihren Gaumen mit unserem himmlischen Schokoladenkuchen.'),
        ('cafebluerose', 'Dessert', 'Zitronen-Lavendel-Tarte', 750, 'Eine erfrischende Tarte mit der perfekten Kombination von Zitrone und Lavendel.'),
        ('cafebluerose', 'Getränk', 'Blumenkohl-Vanille-Latte', 400, 'Ein einzigartiger Latte mit Blumenkohl und einer Hauch von Vanille.'),
        ('cafebluerose', 'Getränk', 'Himbeer-Minz-Eistee', 350, 'Erfrischender Eistee mit frischen Himbeeren und Minze.'),
        ('cafebluerose', 'Getränk', 'Blue Rose Cappuccino', 450, 'Ein spezieller Cappuccino mit dem einzigartigen Geschmack der Blue Rose.'),
        ('cafebluerose', 'Getränk', 'Vanille-Rosenwasser-Limonade', 500, 'Eine erfrischende Limonade mit Vanille und einem Hauch von Rosenwasser.');
        """)
    
    cursor.execute("""
        INSERT or IGNORE INTO Item (Restaurant, Name, IBeschreibung, Kategorie, Preis)
        VALUES ('mamamiapizza', 'Bruschetta', 'mit gehackten Tomaten und frischem Basilikum', 'Vorspeise', 550),
            ('mamamiapizza', 'Caprese-Salat', 'gesalzene rohe Tomatenscheiben mit Mozzarellascheiben, Basilikumblätter in Olivenöl beträufelt', 'Vorspeise', 650);
        """)
                    

    cursor.execute("""
    INSERT or IGNORE INTO Oeffnungszeit (GUsername, Wochentag, Von, Bis)
    VALUES 
        ('cafebluerose', 'Montag', '08:00', '18:00'),
        ('cafebluerose', 'Mittwoch', '08:00', '18:00'),
        ('cafebluerose', 'Donnerstag', '08:00', '18:00'),
        ('cafebluerose', 'Freitag', '08:00', '20:00'),
        ('cafebluerose', 'Sonntag', '10:00', '16:00'),
                   
        ('sushiheaven', 'Dienstag', '12:00', '22:00'),
        ('sushiheaven', 'Mittwoch', '12:00', '22:00'),
        ('sushiheaven', 'Donnerstag', '12:00', '22:00'),
        ('sushiheaven', 'Freitag', '12:00', '23:00'),
        ('sushiheaven', 'Samstag', '12:00', '23:00'),
        ('sushiheaven', 'Sonntag', '12:00', '21:00'),
                   
        ('bowl', 'Montag', '11:00', '20:00'),
        ('bowl', 'Mittwoch', '11:00', '20:00'),
        ('bowl', 'Donnerstag', '11:00', '20:00'),
        ('bowl', 'Freitag', '11:00', '22:00'),
        ('bowl', 'Samstag', '11:00', '22:00'),
        ('bowl', 'Sonntag', '11:00', '19:00'),
                   
        ('americanstory', 'Montag', '17:00', '23:00'),
        ('americanstory', 'Dienstag', '17:00', '23:00'),
        ('americanstory', 'Donnerstag', '17:00', '23:00'),
        ('americanstory', 'Freitag', '17:00', '23:30'),
        ('americanstory', 'Samstag', '17:00', '23:30'),
                   
        ('sidebysoups', 'Montag', '10:00', '19:00'),
        ('sidebysoups', 'Mittwoch', '10:00', '19:00'),
        ('sidebysoups', 'Donnerstag', '10:00', '19:00'),
        ('sidebysoups', 'Samstag', '11:00', '20:00'),
        ('sidebysoups', 'Sonntag', '11:00', '18:00'),
        
        ('mamamiapizza', 'Montag', '16:00', '22:00'),
        ('mamamiapizza', 'Dienstag', '16:00', '22:00'),
        ('mamamiapizza', 'Donnerstag', '16:00', '22:00'),
        ('mamamiapizza', 'Freitag', '16:00', '23:00'),
        ('mamamiapizza', 'Samstag', '12:00', '23:00'),
        ('mamamiapizza', 'Sonntag', '12:00', '21:00'),
                   
        ('zoesgrill', 'Montag', '11:30', '21:00'),
        ('zoesgrill', 'Dienstag', '11:30', '21:00'),
        ('zoesgrill', 'Mittwoch', '11:30', '21:00'),
        ('zoesgrill', 'Donnerstag', '11:30', '21:00'),
        ('zoesgrill', 'Freitag', '11:30', '22:00'),
        ('zoesgrill', 'Samstag', '11:30', '22:00'),
        ('zoesgrill', 'Sonntag', '11:30', '20:00'),
        
        ('sauerkrautundwurst', 'Montag', '11:00', '20:00'),
        ('sauerkrautundwurst', 'Dienstag', '11:00', '20:00'),
        ('sauerkrautundwurst', 'Mittwoch', '11:00', '20:00'),
        ('sauerkrautundwurst', 'Donnerstag', '11:00', '20:00'),
        ('sauerkrautundwurst', 'Freitag', '11:00', '21:00'),
        ('sauerkrautundwurst', 'Samstag', '11:00', '21:00'),
        ('sauerkrautundwurst', 'Sonntag', '12:00', '18:00'),

        ('pilzparadies', 'Montag', '12:00', '21:00'),
        ('pilzparadies', 'Dienstag', '12:00', '21:00'),
        ('pilzparadies', 'Mittwoch', '12:00', '21:00'),
        ('pilzparadies', 'Donnerstag', '12:00', '22:00'),
        ('pilzparadies', 'Freitag', '12:00', '22:00'),
        ('pilzparadies', 'Samstag', '12:00', '22:00'),
        ('pilzparadies', 'Sonntag', '12:00', '20:00'),

        ('schwarzbrotstube', 'Montag', '09:00', '18:00'),
        ('schwarzbrotstube', 'Dienstag', '09:00', '18:00'),
        ('schwarzbrotstube', 'Mittwoch', '09:00', '18:00'),
        ('schwarzbrotstube', 'Donnerstag', '09:00', '18:00'),
        ('schwarzbrotstube', 'Freitag', '09:00', '20:00'),
        ('schwarzbrotstube', 'Samstag', '09:00', '20:00'),
        ('schwarzbrotstube', 'Sonntag', '10:00', '16:00'),

        ('rheinweinhaus', 'Montag', '16:00', '23:00'),
        ('rheinweinhaus', 'Dienstag', '16:00', '23:00'),
        ('rheinweinhaus', 'Mittwoch', '16:00', '23:00'),
        ('rheinweinhaus', 'Donnerstag', '16:00', '23:00'),
        ('rheinweinhaus', 'Freitag', '16:00', '23:30'),
        ('rheinweinhaus', 'Samstag', '12:00', '23:30'),
        ('rheinweinhaus', 'Sonntag', '12:00', '22:00'),

        ('wurstundsenf', 'Montag', '11:30', '20:30'),
        ('wurstundsenf', 'Dienstag', '11:30', '20:30'),
        ('wurstundsenf', 'Mittwoch', '11:30', '20:30'),
        ('wurstundsenf', 'Donnerstag', '11:30', '20:30'),
        ('wurstundsenf', 'Freitag', '11:30', '21:00'),
        ('wurstundsenf', 'Samstag', '11:30', '21:00'),
        ('wurstundsenf', 'Sonntag', '12:00', '18:00'),

        ('zwiebelzirkus', 'Montag', '12:00', '21:00'),
        ('zwiebelzirkus', 'Dienstag', '12:00', '21:00'),
        ('zwiebelzirkus', 'Mittwoch', '12:00', '21:00'),
        ('zwiebelzirkus', 'Donnerstag', '12:00', '22:00'),
        ('zwiebelzirkus', 'Freitag', '12:00', '22:00'),
        ('zwiebelzirkus', 'Samstag', '12:00', '22:00'),
        ('zwiebelzirkus', 'Sonntag', '12:00', '20:00'),

        ('tropicaltaco', 'Montag', '11:30', '21:30'),
        ('tropicaltaco', 'Dienstag', '11:30', '21:30'),
        ('tropicaltaco', 'Mittwoch', '11:30', '21:30'),
        ('tropicaltaco', 'Donnerstag', '11:30', '22:00'),
        ('tropicaltaco', 'Freitag', '11:30', '22:00'),
        ('tropicaltaco', 'Samstag', '11:30', '22:00'),
        ('tropicaltaco', 'Sonntag', '12:00', '20:30'),

        ('saffronspice', 'Montag', '17:00', '22:30'),
        ('saffronspice', 'Dienstag', '17:00', '22:30'),
        ('saffronspice', 'Mittwoch', '17:00', '22:30'),
        ('saffronspice', 'Donnerstag', '17:00', '23:00'),
        ('saffronspice', 'Freitag', '17:00', '23:00'),
        ('saffronspice', 'Samstag', '17:00', '23:00'),
        ('saffronspice', 'Sonntag', '17:00', '22:00'),
        
        ('mysticalmezze', 'Montag', '12:00', '20:00'),
        ('mysticalmezze', 'Dienstag', '12:00', '20:00'),
        ('mysticalmezze', 'Mittwoch', '12:00', '20:00'),
        ('mysticalmezze', 'Donnerstag', '12:00', '21:00'),
        ('mysticalmezze', 'Freitag', '12:00', '21:00'),
        ('mysticalmezze', 'Samstag', '12:00', '21:00'),
        ('mysticalmezze', 'Sonntag', '12:00', '19:00'),

        ('cocoacraze', 'Montag', '08:00', '18:00'),
        ('cocoacraze', 'Dienstag', '08:00', '18:00'),
        ('cocoacraze', 'Mittwoch', '08:00', '18:00'),
        ('cocoacraze', 'Donnerstag', '08:00', '19:00'),
        ('cocoacraze', 'Freitag', '08:00', '19:00'),
        ('cocoacraze', 'Samstag', '10:00', '19:00'),
        ('cocoacraze', 'Sonntag', '10:00', '17:00'),

        ('thaiharmony', 'Montag', '17:00', '22:00'),
        ('thaiharmony', 'Dienstag', '17:00', '22:00'),
        ('thaiharmony', 'Mittwoch', '17:00', '22:00'),
        ('thaiharmony', 'Donnerstag', '17:00', '23:00'),
        ('thaiharmony', 'Freitag', '17:00', '23:00'),
        ('thaiharmony', 'Samstag', '12:00', '23:00'),
        ('thaiharmony', 'Sonntag', '12:00', '22:00'),

        ('stellarsteaks', 'Montag', '18:00', '23:00'),
        ('stellarsteaks', 'Dienstag', '18:00', '23:00'),
        ('stellarsteaks', 'Mittwoch', '18:00', '23:00'),
        ('stellarsteaks', 'Donnerstag', '18:00', '23:30'),
        ('stellarsteaks', 'Freitag', '18:00', '23:30'),
        ('stellarsteaks', 'Samstag', '17:30', '23:30'),
        ('stellarsteaks', 'Sonntag', '17:30', '22:30'),

        ('greenoasiscafe', 'Montag', '08:00', '18:00'),
        ('greenoasiscafe', 'Dienstag', '08:00', '18:00'),
        ('greenoasiscafe', 'Mittwoch', '08:00', '18:00'),
        ('greenoasiscafe', 'Donnerstag', '08:00', '19:00'),
        ('greenoasiscafe', 'Freitag', '08:00', '19:00'),
        ('greenoasiscafe', 'Samstag', '10:00', '19:00'),
        ('greenoasiscafe', 'Sonntag', '10:00', '17:00'),

        ('spicynoodlehouse', 'Montag', '11:30', '21:30'),
        ('spicynoodlehouse', 'Dienstag', '11:30', '21:30'),
        ('spicynoodlehouse', 'Mittwoch', '11:30', '21:30'),
        ('spicynoodlehouse', 'Donnerstag', '11:30', '22:00'),
        ('spicynoodlehouse', 'Freitag', '11:30', '22:00'),
        ('spicynoodlehouse', 'Samstag', '11:30', '22:00'),
        ('spicynoodlehouse', 'Sonntag', '12:00', '20:30'),

        ('fusiondelight', 'Montag', '12:00', '20:00'),
        ('fusiondelight', 'Dienstag', '12:00', '20:00'),
        ('fusiondelight', 'Mittwoch', '12:00', '20:00'),
        ('fusiondelight', 'Donnerstag', '12:00', '21:00'),
        ('fusiondelight', 'Freitag', '12:00', '21:00'),
        ('fusiondelight', 'Samstag', '12:00', '21:00'),
        ('fusiondelight', 'Sonntag', '12:00', '19:00'),

        ('sunsetgrill', 'Montag', '17:00', '22:30'),
        ('sunsetgrill', 'Dienstag', '17:00', '22:30'),
        ('sunsetgrill', 'Mittwoch', '17:00', '22:30'),
        ('sunsetgrill', 'Donnerstag', '17:00', '23:00'),
        ('sunsetgrill', 'Freitag', '17:00', '23:00'),
        ('sunsetgrill', 'Samstag', '17:00', '23:00'),
        ('sunsetgrill', 'Sonntag', '17:00', '22:00'),
        
        ('kfp', 'Montag', '11:00', '22:00'),
        ('kfp', 'Dienstag', '11:00', '22:00'),
        ('kfp', 'Mittwoch', '11:00', '22:00'),
        ('kfp', 'Donnerstag', '11:00', '23:00'),
        ('kfp', 'Freitag', '11:00', '23:00'),
        ('kfp', 'Samstag', '11:00', '23:00'),
        ('kfp', 'Sonntag', '11:00', '22:00'),

        ('subday', 'Montag', '09:00', '20:00'),
        ('subday', 'Dienstag', '09:00', '20:00'),
        ('subday', 'Mittwoch', '09:00', '20:00'),
        ('subday', 'Donnerstag', '09:00', '21:00'),
        ('subday', 'Freitag', '09:00', '21:00'),
        ('subday', 'Samstag', '10:00', '21:00'),
        ('subday', 'Sonntag', '10:00', '20:00'),

        ('mcdaniels', 'Montag', '00:00', '23:59'),
        ('mcdaniels', 'Dienstag', '00:00', '23:59'),
        ('mcdaniels', 'Mittwoch', '00:00', '23:59'),
        ('mcdaniels', 'Donnerstag', '00:00', '23:59'),
        ('mcdaniels', 'Freitag', '00:00', '23:59'),
        ('mcdaniels', 'Samstag', '00:00', '23:59'),
        ('mcdaniels', 'Sonntag', '00:00', '23:59');
""")

    dbcon.commit()
    dbcon.close()